### ISSUE TITLE
Make banned option useful under BungeeCord

### ISSUE THREAD

**Issue by Phoenix616** [Minecrell/ServerListPlus#102]
Currently whether or not a user is banned can only be set via the Minecraft server's banlist. This should work well for every ban plugin on the Minecraft server side but wont work for BungeeCord as it doesn't have an API for that. (The current implementation just returns false there)

One of the possible ways would probably be an event Bungee ban plugins could listen to which the BungeePlugin.isBanned() method fires. (Bungee does a similar thing with permission checks for example)

**Comment by MineTheCube** [comment]
Instead of firing an event each time ping occurs, why not using kind of listener, like:

```java
ServerListPlus.registerBanHandler(new BanHandler() {
  public boolean isBanned(Channel/UUID/String user) {
    return banMap.get(user) != null;
  }
});

**Comment by Phoenix616** [comment]
How would this be any better than using the event system that is already in
place?

**Comment by MineTheCube** [comment]
It would avoid creating a new object at every single ping. Since it could happen a lot, *I think* it would be more memory-efficient and faster to use a listener.

**Comment by Minecrell** [comment]
@MineTheCube An event provides more flexibility with priorities and is much easier to hook into than having to implement a separate API for each plugin you want to hook in.
Additionally a single object allocation is quite cheap, BungeeCord already creates an event for each ping. It would only matter if a lot of object allocations are required which is not the case for the event system.

**Comment by Minecrell** [comment]
https://github.com/Minecrell/ServerListPlus/pull/201 added an API for this plus support for some ban plugins on BungeeCord.
