### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by Minecrell** [Minecrell/ServerListPlus#104]
I'm going to split the configuration in separate files instead of the sections because it was just too confusing, often people just added the options in the wrong section.

- [x] Choose configuration format
- [x] Split configuration files

**Comment by Minecrell** [comment]
TODO: Need to decide if I want to keep YAML as configuration format

**Comment by Minecrell** [comment]
HOCON sucks

**Comment by liach** [comment]
json?

**Comment by Minecrell** [comment]
Not exactly user friendly, you always need the quotes and it really, really sucks for multiline strings (because you would need to do `\n`)

**Comment by Minecrell** [comment]
YAML will stay for now. I'll try to make it more abstract in a way that allows extending it later.

**Comment by Minecrell** [comment]
Completed in https://github.com/Minecrell/ServerListPlus/commit/4d8df472599ced4c0b441b240578cbcc4b964d9b
