### ISSUE TITLE
MYSQL support

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#108]
Hello,

Could you add MYSQL support ?

**Comment by Minecrell** [comment]
For? What would be saved there?

**Comment by TheIntelloBox** [comment]
The PlayerCaches.

**Comment by Minecrell** [comment]
Ah, see https://github.com/Minecrell/ServerListPlus/issues/44 :)

**Comment by TheIntelloBox** [comment]
Thanks.
