### ISSUE TITLE
Add a cache to Favicon URLs

### ISSUE THREAD

**Issue by xXAndrew28Xx** [Minecrell/ServerListPlus#111]
Close this request (issue) if it is already implemented but when my players ping sometimes it takes a while, the URL is http://tntwars.net/favicon.php?uuid=7b6105779d3047399e0a6668a4d6a70c and returns instantly for me.

**Comment by Minecrell** [comment]
They're already cached, but the website may behave differently if they have a lot of requests concurrently. Only the first load will take longer, but this is nothing that is preventable except using a different service

**Comment by xXAndrew28Xx** [comment]
OK, thanks so much.
