### ISSUE TITLE
Server out of Date

### ISSUE THREAD

**Issue by Nosxxx** [Minecrell/ServerListPlus#112]
Hallo,
ich bekomme seit dem Update auf 1.10 eine Out of Date Message in der Übersicht. Joinen kann ich meinen Server, wenn ich dein Plugin deaktiviere funktioniert es auch prima. Gibts hier vielleicht einen bekannten Bug? 

https://www.dropbox.com/s/q5d2knm87sl41ux/Screenshot%202016-06-20%2011.16.11.png?dl=0

**Comment by Minecrell** [comment]
Welche BungeeCord Version verwendest du? (Steht irgendwo in der Konsole, bzw. wenn du `/bungee` eingibst)

**Comment by Nosxxx** [comment]
20.06.2016 11:08 [INFORMATION] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:6f6cb58:1161

**Comment by Minecrell** [comment]
Außerdem benötige ich auch noch eine Kopie deiner Konfiguration, damit ich das Problem nachvollziehen kann.

**Comment by Nosxxx** [comment]
https://www.dropbox.com/s/ek1awi5pbfa6fwm/ServerListPlus.yml?dl=0

**Comment by Minecrell** [comment]
Ich kann das Problem nachvollziehen und versuche jetzt eine Lösung zu finden, vielen Dank für deine Benachrichtigung!

**Comment by Minecrell** [comment]
Behoben in https://github.com/Minecrell/ServerListPlus/commit/f2d5ec6a840cb4225d1b7ac93008a0f8de299711, neue Version kommt dann gleich.

**Comment by Minecrell** [comment]
Bitte lade die neuste BungeeCord Version und die neuste ServerListPlus Version von https://github.com/Minecrell/ServerListPlus/releases/tag/3.4.6 herunter, die sollten das Problem beheben.

**Comment by Nosxxx** [comment]
Danke läuft super.
