### ISSUE TITLE
Disable Player Count Hover Player Count

### ISSUE THREAD

**Issue by BrettplayMC** [Minecrell/ServerListPlus#113]
I am wondering if in ServerListPlus 4.0 you could add an option to disable the players shown when you hover over the server player count?  This could be useful if we don't want the hover feature but we want to have the player count.

**Comment by Someone-NEW** [comment]
I have a problem with the latest version that Hover is not to see Player counts work but i see Client out of date! and Hover is not to see Server is 1.10.2 my launcher is 1.10.2 but still not see my Hover can you please fix that?

**Comment by Minecrell** [comment]
@Someone-NEW Please open a new issue if you need help. Do you get an error on your server?

**Comment by Someone-NEW** [comment]
Sorry, no i have no error but i found something info here that is so strange but i CANT use Hover whatever i do.
https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots

**Comment by Minecrell** [comment]
@Someone-NEW Please open a new issue here: https://github.com/Minecrell/ServerListPlus/issues/new

**Comment by Minecrell** [comment]
You can now use:

```yaml
  Players:
    Hover: off
```

to disable it entirely in 3.5.0.

**Comment by SoheylRF** [comment]
Please add this on github wiki as well
