### ISSUE TITLE
Edit MOTD in-game

### ISSUE THREAD

**Issue by Snipershotmaster** [Minecrell/ServerListPlus#119]
I have a request. Can it be possible to introduce a command that would update the motd in-game? Something like that would be great for a minigame server that can update their motd that can display their current status.

An example format of that command can be: "/slp edit [Default,Personalized,Both] [message number] [line number] [message]"

The first option allows the user to choose which motd to edit. The second option would choose which motd message to edit. The line number would choose which line to edit. Finally, the new message you would want to introduce.

I thought this can be a new feature in 4.0 :)

**Comment by Minecrell** [comment]
Thank you for your request, see https://github.com/Minecrell/ServerListPlus/issues/20.

Currently, I don't plan adding that in 4.0. In my opinion it is almost always easier to make the changes in the configuration directly, so I spent additional time making sure the configuration is as easy and flexible as possible.

To achieve the same using commands, as in your example, you would always need to execute several commands only to create a small configuration. It would be possible to build a more interactive ingame editor (e.g. you start editing and can just type the lines you want to add then), but that would take quite a lot of time to develop.

Are you looking for a way to update the SLP configuration automatically within a minigame, or do you want to execute the commands to update the status manually?

**Comment by Snipershotmaster** [comment]
Hey sorry for the late response, but yes, I would like to update the SLP configuration automatically.

**Comment by Minecrell** [comment]
So would you basically have a minigame that executes this command? The reason I'm asking is simply whether an API other plugins could hook into would already be enough.

**Comment by Snipershotmaster** [comment]
Yes, having the minigame to execute the command would probably be the most efficient way of setting up a dynamic motd. I'm not much of a programmer yet so I wouldn't know how to change the motd with the API.
