### ISSUE TITLE
 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Rocologo** [Minecrell/ServerListPlus#121]
Today I found this error in my console log. 

http://pastebin.com/HgZhCMK3

It looks like the same error like the one i reported previously #117 but again the stacktrace is not completely the same so I decided to report it. 

You can close the ticket if you think it is the same.

**Comment by Minecrell** [comment]
Thank you for your report. I'm pretty sure it is caused by the same problem which I will attempt to fix in 4.0.
