### ISSUE TITLE
how do you use UTF-8 charset?

### ISSUE THREAD

**Issue by rubota** [Minecrell/ServerListPlus#125]
u01A0, u+01A0, (u01A0), (u+01A0), /u01A0, and Ơ. Non of these work. The symbol itself shows up as nothing and the reset of the codes show up exactly as presented here - no actual symbol can be displayed. 

How do I make it so symbols can be displayed?

**Comment by Minecrell** [comment]
Does the server print an error if you copy the symbol directly? iirc Minecraft does not support all symbols.

**Comment by rubota** [comment]
It doesn't show any errors. If I place the symbol directly into the config and then save, the symbol disappears. I've tried several dozen different types of symbols and codes

**Comment by Minecrell** [comment]
Which editor are you using to edit the configuration?

**Comment by rubota** [comment]
I just want an example of how it's suppose to be written in the config.

**Comment by rubota** [comment]
I'm not using an editor, just trying to see which way i'm suppose to place the code into the config. The config works fine until I try to add a utf-8 code. 

If not many symbols work, is there a list of the very limited symbols that do?

**Comment by Minecrell** [comment]
They are supposed to be copied directly into the configuration. Then the configuration must be saved with UTF-8 (you can configure this for example in Notepad++ on Windows). Please try using `»` or `«`, I'm sure these should work.

**Comment by rubota** [comment]
I've actually tried both of those symbols, neither of them work and i'm on a mac

**Comment by rubota** [comment]
I can't even save with those symbols, it shows up as "an internal error occurred while reloading the configuration." I'm sure you know this, but that error means it would of reset the config if I restarted the server.

**Comment by Minecrell** [comment]
Please paste your server log.

**Comment by rubota** [comment]
http://pastebin.com/zr1B0mHG

**Comment by rubota** [comment]
lol, i think i just figured it out. I was ignoring the protocol lib warning because this is a testing server and thought it was for something else

**Comment by rubota** [comment]
I'll install it and see if it fixes the issue

**Comment by Minecrell** [comment]
The last error means your configuration is not getting saved using UTF-8 which explains why it doesn't work.

**Comment by rubota** [comment]
Actually never mind, I already have the procollib installed

**Comment by rubota** [comment]
how do i save it as utf-8?

**Comment by jamierocks** [comment]
What text editor are you using?

**Comment by rubota** [comment]
I'm not, I'm on a mac

**Comment by jamierocks** [comment]
The operating system you use is irrelevant, to modify a file you need to use a text editor (I use vscode for example)

**Comment by rubota** [comment]
I think I could prob figure out how to do it if I had an example. I believe Minecrell said all I have to do is paste the symbol into the config. But it's not saving as utf-8 and I don't know how to save it as utf-8

**Comment by rubota** [comment]
I couldn't just do it by hand? All I want to do is add a simple symbol

**Comment by jamierocks** [comment]
If you tell me what text editor you're using I can investigate how to save in utf-8 for you.

**Comment by rubota** [comment]
I don't use any text editor. I've always done it by hand

**Comment by rubota** [comment]
Maybe this is just not meant to be.

**Comment by rubota** [comment]
ah, apparently I have one. Is textedit one? Names can be misleading. According to wikipedia it is

**Comment by jamierocks** [comment]
I'm going to assume you're using TextEdit (macOS' default text editor)

1. Navigate to the TextEdit Preferences (TextEdit->Preferences) ![http://i.lexteam.xyz/NWNUt0ZnQe.png](http://i.lexteam.xyz/NWNUt0ZnQe.png)

2. Switch to the `Open and Save` tab (Open and Save) ![http://i.lexteam.xyz/yVqpWvmHot.png](http://i.lexteam.xyz/yVqpWvmHot.png)

3. Under `Plain Text File Encoding` change `Saving files` to `Unicode (UTF-8)` ![http://i.lexteam.xyz/s4Ut1dg1jM.png](http://i.lexteam.xyz/s4Ut1dg1jM.png)

4. You're done!

**Comment by rubota** [comment]
ooooh, Thank you! Now to see if it works

**Comment by rubota** [comment]
Yeah, it didn't work

**Comment by rubota** [comment]
When I saved it and reloaded the document, nothing changed, it stayed as a symbol. I loaded the config onto the server and it did the same as every other time - disappeared.

**Comment by jamierocks** [comment]
Hmm - any chance you could throw your config on [Gist](https://gist.github.com/)?

**Comment by rubota** [comment]
https://gist.github.com/rubota/b5e7fb3f1b3bf2c439fe2e7efa337cb2

**Comment by rubota** [comment]
&0.       &c➣    &c&m-&6&m-&e&m-&a&m-&d&m-&r  &l&1R&3a&ai&en&6b&co&4w&5N&da&bt&3i&ao&en  &d&m-&a&m-&e&m-&6&m-&c&m-
    &0.&r                  &aSummer Sale Event

is the line

**Comment by rubota** [comment]
Do you have an example of how to save it as utf-8? I can just edit your save. Might be a lot easier than this.

**Comment by Minecrell** [comment]
Your configuration works fine for me:

![screenshot_20160811_184755](https://cloud.githubusercontent.com/assets/3035868/17596994/2e83671e-5ff4-11e6-8bac-43e3556c522f.png)

Please note the following though:

- You have the symbol only in the `Personalized` section, therefore it will only show if you have already logged in in the server once.
- You only have the symbol in one of the `Personalized` messages, (the one without the player name), so it will only show every few refreshes because otherwise the other message is shown.

**Comment by rubota** [comment]
Believe me, i've refreshed it hundreds of times. It doesn't show up

**Comment by rubota** [comment]
It doesn't even save in the config. If i put the symbol into the config and then save, it disappears when I check it again.

**Comment by jamierocks** [comment]
Do you always get the exception from your above stacktrace or does it just not show now?

**Comment by rubota** [comment]
before save: &0.       &c➣ ✫ ⍉  ☁︎ &c&m-&6&m-&e&m-&a&m-&d&m-&r  &l&1R&3a&ai&en&6b&co&4w&5N&da&bt&3i&ao&en  &d&m-&a&m-&e&m-&6&m-&c&m-

after save: &0.       &c     &c&m-&6&m-&e&m-&a&m-&d&m-&r  &l&1R&3a&ai&en&6b&co&4w&5N&da&bt&3i&ao&en

**Comment by rubota** [comment]
the exception only show'd up when used those two specific special characters. The message hasn't show'd up for any other symbol

**Comment by jamierocks** [comment]
Have you enabled slp? `/slp enable`

**Comment by rubota** [comment]
yeah, I said It's already enabled. The message shows everything except the symbol. It disappears in the config right after i save it

**Comment by jamierocks** [comment]
Try using [vscode](https://code.visualstudio.com/) as the text editor.

**Comment by rubota** [comment]
Thank you for staying so long and trying to help me. This is becoming tiresome. I don't want to learn a new language, I just wanted to add a symbol. Some things are just not meant to be, and apparently this is one of them. 

Thanks again

**Comment by rubota** [comment]
s12.hosthorde.com:26008. 

I've copied the message so that regardless if you're new or returning, the message says the same. No symbol is present regardless of what I do or how much effort I put into it.

**Comment by Minecrell** [comment]
As a last suggestion, you can try saving https://gist.githubusercontent.com/Minecrell/d00d77b982af7b7a8e36796bf138b7c7/raw/d46b7ea8954da93b53bcd5d372c855d274cd6f57/ServerListPlus.yml as-is and copying the file to your SLP config dir. Make sure to make a backup of your old file.

This configuration should always show the symbol. (First try not opening it using your editor, just copy the file)

**Comment by rubota** [comment]
Same thing happened, It disappeared. 

http://pastebin.com/hL0sR3Xa

**Comment by Minecrell** [comment]
It must be an issue with your system.

Anyway, as an alternative ServerListPlus supports bypassing pasting the symbols directly, using a slightly different syntax:

```yaml
  Description:
    - "&0.       &c\u27A3    &c&m-&6&m-&e&m-&a&m-&d&m-&r\n&l&1R&3a&ai&en&6b&co&4w&5N&da&bt&3i&ao&en  &d&m-&a&m-&e&m-&6&m-&c&m-"
```

- You have to separate new lines using `\n`
- Replace the special character using the following form: `\u27A3` (you can usually find the corresponding unicode code point using Google)

**Comment by rubota** [comment]
I've tried that before. It shows up exactly as \u27A3

**Comment by rubota** [comment]
You're welcome to have a look at s12.hosthorde.com:26008.

**Comment by Minecrell** [comment]
It works only inside of double quotes (the same way I used it above)

**Comment by rubota** [comment]
lol, I copied exactly what you put and it shows up exactly as you put it - quotations and all.

**Comment by rubota** [comment]
<img width="649" alt="screen shot 2016-08-11 at 12 26 47 pm" src="https://cloud.githubusercontent.com/assets/12865829/17598174/e98537bc-5fbe-11e6-9c44-bee8e5554dad.png">

**Comment by Minecrell** [comment]
It should be like this: https://gist.github.com/Minecrell/d00d77b982af7b7a8e36796bf138b7c7#file-serverlistplus-yml-L34-L50

**Comment by rubota** [comment]
Oh, that one worked. Suppose I'll use this as a template. Thank you

**Comment by rubota** [comment]
I'm still curious on why simple symbols won't work.

**Comment by rubota** [comment]
But perhaps that's irreverent I should be happy I have a proper template now. 
Thanks again for not abandoning me.

**Comment by Minecrell** [comment]
It must be either related to the editor you are using (TextEdit) or your system itself. ServerListPlus will load it correctly if it is saved correctly, and I also tested that it works properly with your configuration.

If you have some spare time the next days you can still try using another editor (e.g. vscode @jamierocks posted, or [Atom](https://atom.io)) which may solve these issues. (I use Atom and used your configuration without any problems.)

Otherwise the fallback will also do the job I guess, although it is not that nicely readable. Since a solution was found I'm closing this issue for now. Feel free to comment here or create a new issue if you have another question! :smile:

**Comment by rubota** [comment]
Just a suggestion, but it would probably be a big help for those who are code illiterate if there was a template example incase this problem arrises again.

**Comment by Minecrell** [comment]
Thanks for the suggestion, I will make sure to add it together with ServerListPlus v4.0 since that will require a major wiki overhaul anyway.

**Comment by jamierocks** [comment]
Just as a suggestion I've heard many bad things about HostHorde (namely they don't keep Java up to date, etc), so perhaps an alternative host is worth a look (perhaps one which gives you a dedicated ip?)

**Comment by rubota** [comment]
Yeah, I was thinking of migrating hosts. I mainly use this one for testing though. Any specific one you'd recommend?

**Comment by jamierocks** [comment]
My recommendation would be [NodeCraft](https://nodecraft.com/r/neptune) - they have a custom panel, and they really make the whole procedure super easy.

**Comment by jamierocks** [comment]
And if you want 15% off your first month the discount code `Neptune` should work.

**Comment by rubota** [comment]
I noticed they have dedicated ip's as standard. Suppose the price represents the service.

**Comment by jamierocks** [comment]
NodeCraft have very reasonable prices, and much like many others that provide dedicated ips has a similar pricing structure.
