### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by Ompalompa00** [Minecrell/ServerListPlus#129]
Using the newest version, and i keep getting this error, why?
24.08 15:08:06 [Server] ERROR [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
24.08 15:08:06 [Server] INFO java.lang.NullPointerException
24.08 15:08:06 [Server] ERROR Parameters: 
24.08 15:08:06 [Server] INFO net.minecraft.server.v1_10_R1.PacketHandshakingInSetProtocol@48fa2549[

**Comment by Ompalompa00** [comment]
And this earlier:
24.08 14:57:58 [Server] ERROR [ServerListPlus] Unhandled exception occured in onPacketReceiving(PacketEvent) for ServerListPlus
24.08 14:57:58 [Server] INFO java.lang.NullPointerException
24.08 14:57:58 [Server] INFO at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_92]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.withType(StructureModifier.java:456) ~[ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.events.PacketContainer.getProtocols(PacketContainer.java:709) ~[ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at net.minecrell.serverlistplus.bukkit.handlers.ProtocolLibHandler$StatusPacketListener.onPacketReceiving(ProtocolLibHandler.java:63) ~[ServerListPlus-3.4.6-Universal%20(1).jar:?]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib%20(1).jar:4.0.2-SNAPSHOT-b293]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at net.minecraft.server.v1_10_R1.LegacyPingHandler.channelRead(SourceFile:94) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot-latest.jar:git-Spigot-1e4dd71-4db0855]
24.08 14:57:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
24.08 14:57:58 [Server] ERROR Parameters: 
24.08 14:57:58 [Server] INFO net.minecraft.server.v1_10_R1.PacketHandshakingInSetProtocol@4f404cfe[

**Comment by Minecrell** [comment]
That looks like a problem in ProtocolLib. Is it up to date?

**Comment by Ompalompa00** [comment]
I can check!

**Comment by Ompalompa00** [comment]
Okey, using the newest version of ProtocolLib now, No errors yet :+1:
