### ISSUE TITLE
Favicon Heads URL

### ISSUE THREAD

**Issue by EazyFTW** [Minecrell/ServerListPlus#130]
**Getting This Error:**

[Server] WARNING [Core] Unable to load favicon from URL: https://mc-heads.net/head/0558982295db4a8cbec56aab3550caa5/64 -> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by Minecrell** [comment]
Have you tried http://cravatar.eu/?

**Comment by EazyFTW** [comment]
I will try it now

**Comment by EazyFTW** [comment]
It worked Thanks
