### ISSUE TITLE
[ServerListPlus] Unhandled exception occured in onPacketSending(PacketEvent) for ServerListPlus java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by ElliotPoots** [Minecrell/ServerListPlus#131]
So, recently - for some reason, me and my users are unable to see the contents of the "Hover" feature... The plugin was working perfectly fine before, and all of a sudden stopped-working.
Full error code: http://pastebin.com/aw3dmgeX

Thank you.

**Comment by ElliotPoots** [comment]
Thought I should mention, I have updated both ProtocolLib and ServerListsPlus to their most updated versions. I tried the latest Dev Build for ProtocolLib also.

**Comment by Minecrell** [comment]
It looks more like a ProtocolLib issue to be honest. Are you using Minecraft 1.8? If so, you could try using an older ProtocolLib build, e.g. ProtocolLib 3.6.5: https://www.spigotmc.org/resources/protocollib.1997/download?version=69182

**Comment by ElliotPoots** [comment]
Fixed it immediately. Sorry for bothering you. 

Thanks for the solution :+1:

**Comment by Minecrell** [comment]
Awesome, good to know this is a possible fix. :)
