### ISSUE TITLE
Player cache does not update names and UUIDs

### ISSUE THREAD

**Issue by RoboMWM** [Minecrell/ServerListPlus#132]
It doesn't seem like it ever does, e.g. if a player changes their name or another player logs in. My brother always gets my name in the server list, even when I haven't joined the server from that IP for months.

**Comment by Minecrell** [comment]
Unless something is broken, the player cache should just map the IPs to the player that was most recently online with the IP. Once a player has logged in to the server again it should also update the name if it was changed since the last login.

**Comment by RoboMWM** [comment]
> the player cache should just map the IPs to the player that was most recently online with the IP

This hasn't been happening for the past several 3.4.x versions (i.e., as long as I've been using it). I'm now using the bungee one, but neither has ever updated with my brother's MC name.

**Comment by Minecrell** [comment]
Looking at the code I think you're right. It will only update the last logged in date if an entry already exists.

**Comment by Minecrell** [comment]
This should be fixed now. Would you mind testing the latest development build from: https://ci.minecrell.net/job/ServerListPlus/

Please let me know if that fixes the issue for you. :)

**Comment by RoboMWM** [comment]
My brother claims it works, so I guess it's fixed, thanks!
