### ISSUE TITLE
Special Symbol.

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#134]
Hello,

Where can we add special symbol ? 
http://zupimages.net/up/16/37/p7vu.jpg

Thanks ! :D

**Comment by Minecrell** [comment]
You can paste them directly into your configuration, but make sure to save the configuration as UTF-8, (on Windows you can use an editor like Notepad++ to configure that easily).

**Comment by TheIntelloBox** [comment]
Where can I find it ?

**Comment by Minecrell** [comment]
Oh, I can't help you with that, but http://unicode-table.com might be useful to you. Click on a symbol you want to use, then copy it into your configuration.
