### ISSUE TITLE
Error with Spaces?

### ISSUE THREAD

**Issue by Tabonosh** [Minecrell/ServerListPlus#135]
If i try to edit the Description or the Player Hover and i try to make it center and save and reload it gives a whole load of errors and disables itself.
Help?

**Comment by Minecrell** [comment]
You can prefix the spaces with a color code to fix the errors.

**Comment by Tabonosh** [comment]
doesn't work with the Player Overlay since if you just space it out it continues the Box.

**Comment by Minecrell** [comment]
Can you post your configuration on something like Pastebin and copy the link here? Then I can try to reproduce your problem.

**Comment by Tabonosh** [comment]
http://pastebin.com/TKdHTHRB

**Comment by Minecrell** [comment]
What do you mean with "it continues the box"? The player hover box doesn't have a fixed size so you will need to align it according to the longest lines. (Or add spaces at the end with a color code after it).
