### ISSUE TITLE
Unknown configuration property: URLs @ FaviconConf

### ISSUE THREAD

**Issue by Bayside308** [Minecrell/ServerListPlus#136]
Hello!

I'm trying to use the bust example from the ServerListPlus wiki, but it doesn't seem to work. In console, it says:

> Unknown configuration property: URLs @ FaviconConf

[This](http://pastebin.com/fZNWqaEf) is my config. I'm running the latest "Waterfall" version and the latest ServerListPlus version.

**Comment by Minecrell** [comment]
You added the favicon option in the wrong configuration section. You need to add it within the !Status section. Please take a look at the example configuration: https://github.com/Minecrell/ServerListPlus/wiki/Examples

**Comment by Bayside308** [comment]
That was a dumb mistake on my part, thanks for the help!
