### ISSUE TITLE
VirtualHost feature doesn't work with clients connecting from Forge

### ISSUE THREAD

**Issue by ColtonDRG** [Minecrell/ServerListPlus#139]
Clients who have Forge installed don't get to see the special VirtualHost stuff. It seems to work OK with unmodded clients and LiteLoader clients, but whenever I connected to a VirtualHost from Forge, I only got the default server message. I couldn't find this documented anywhere, but correct me if I missed something.

Also, this is slightly unrelated, but I couldn't seem to get the VirtualHosts feature to work when connecting to an SRV record. For example, if I made an SRV record for _minecraft._tcp.example.com pointing to 25565 example.net, and added an entry to the SLP file for example.com, I would get the default server message, not the example.com VirtualHost one. I figured this had something to do with the way Minecraft actually pings the server and there was nothing you could do about it, so I just worked around it by pointing a subdomain like exampledotcom.example.net to the IP and pointing the SRV record for example.com to 25565 exampledotcom.example.net and adding a VirtualHost config for exampledotcom.example.net instead. This workaround works alright.

**Comment by Minecrell** [comment]
Which platform are you using SLP on?

**Comment by ColtonDRG** [comment]
Paper (Spigot)

**Comment by Minecrell** [comment]
You're right, it seems to be broken on Spigot.

**Comment by Minecrell** [comment]
This seems to affect all platforms except BungeeCord.

**Comment by Minecrell** [comment]
Should be fixed:
- Fix for Bukkit/Spigot/Paper, Standalone server and CanaryMod: https://github.com/Minecrell/ServerListPlus/commit/3a5d2934a3347dd726071664a7b3ffdf4e33c046
- Sponge fix: https://github.com/SpongePowered/SpongeCommon/commit/e6fa6cf3553549e576eee515eb002ea64169b541

Since there are not any other changes yet, I'm not going to make a new release just with this fix. Feel free to use the development versions in the meantime (there were no other changes, so they should be as stable as the latest release).

I've also fixed something related to SRV records. Please test if the workaround is still necessary.

**Comment by ColtonDRG** [comment]
The Forge fix worked, thanks. The SRV fix did not, but the workaround is still acceptable for now.

**Comment by Minecrell** [comment]
The Minecraft client handles SRV clients separately from the connection, so it will always use the hostname specified in the SRV record together with the port as virtual host (and not the hostname the player entered originally).

You can, however have a SRV record pointing to itself to solve this problem. E.g. if you have a SRV record `example.com` to `example.com:25565` it will stay as `example.com` (you still need an A record on `example.com` pointing to the actual IP).

**Comment by ColtonDRG** [comment]
Yes, I expected that was the case, and I was aware of that workaround, but in this case I'm using this workaround to point the Minecraft server to a different server from the one that that domain's other services such as http are hosted on. For this reason, obviously, the A record needs to point to a different IP than the Minecraft server, so the SRV record is used to make Minecraft know where the actual server is. This breaks the VirtualHost system in SLP, so in order to work around that, I just used the method described in the first post. That's a dirty hack, but it works fine. :)
