### ISSUE TITLE
NPE on whitelisted quit.

### ISSUE THREAD

**Issue by ryantheleach** [Minecrell/ServerListPlus#140]
http://hastebin.com/qesufenagi.hs

I tried to look at the source to debug, but since everything is on one line there I wasn't able to check before having to move onto debugging my own plugins for the server owner.

**Comment by Minecrell** [comment]
Your hastebin doesn't exist for some reason, can you upload it again?

**Comment by ryantheleach** [comment]
I'm sorry,  I'm not sure I can.

**Comment by Minecrell** [comment]
Seems like the paste works again now, however the issue you mentioned is caused by https://github.com/SpongePowered/SpongeForge/issues/527
