### ISSUE TITLE
New Placeholder

### ISSUE THREAD

**Issue by LuckyLuckiest** [Minecrell/ServerListPlus#144]
Could you add a placeholder that allows you make the MOTD centered ?
Like in Mineplex, hypixel, ... etc.
It would be cool if you add this to the plugin, and it would make the sever alot more professional!

**Comment by Minecrell** [comment]
You can manually center your MOTD using spaces. At some point I will check if there is an easy way to add this, like described in https://github.com/Minecrell/ServerListPlus/issues/106
