### ISSUE TITLE
1.11 Support.

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#145]
Hello,

Could you add 1.11 support ? :D 

Thanks ! :)

**Comment by Minecrell** [comment]
Do you get an error? Normally it should not need any updating.

**Comment by TheIntelloBox** [comment]
I didn't test, but all the plugins are update, so I thought that ServerListPlus must too.

**Comment by Minecrell** [comment]
If you are using the Spigot version I can imagine that you need a ProtocolLib update. Otherwise it should continue to work fine. Let me know if you get an error!
