### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by plop40** [Minecrell/ServerListPlus#146]
to have more PlaceHolder :)

Thanks for the hard work.

**Comment by Minecrell** [comment]
Unfortunately that is impossible as far as I know because PlaceholderAPI requires the player to be online if you want to get placeholders for him.

**Comment by lasercar** [comment]
This could be useful for things like displaying the online players with their ranks/nicknames in the hover list.

**Comment by Sir-Will** [comment]
@Minecrell hm, but PlaceholderAPI doesn't only support players but also other stuff.
See: https://www.spigotmc.org/wiki/placeholderapi-placeholders/

**Comment by Minecrell** [comment]
Apparently, PlaceholderAPI does support passing `null` as player for the few placeholders that don't depend on a specific user. This could be supported in ServerListPlus.

**Comment by Flavourized** [comment]
@extendedclip

**Comment by extendedclip** [comment]
I plan on converting the placeholder system to use OfflinePlayer instead of Player in 3.0 but that is not going to be released for a while.  I would say it's currently not worth adding support just yet as there are very few placeholders that do not require a player.

**Comment by SlimeDog** [comment]
Even without player data, it would be very useful to have server-level placeholders like
- multiverse_world_alias
- viaversion_player_protocol_version

**Comment by BrettplayMC** [comment]
I would like to be able to display server info, countdowns, etc via placeholderapi.
Also 3.0 is almost here so can we get it in v3 of SLP possibly? https://www.spigotmc.org/resources/placeholderapi.6245/update?update=276844

**Comment by BrettplayMC** [comment]
Going to bump this dinosaur.

**Comment by Flavourized** [comment]
@BrettplayMC crazy guy

**Comment by SlimeDog** [comment]
#247 suggests that motivation might move this issue along. I would use the same ServerListPlus.yml on a cluster of servers, thus simplifying my configuration, except that %server_name% is not supported, so the file is different on each server. Please reconsider adding a few server-based placeholders, either through PlaceholderAPI or just adding them to SLP. I am willing to add modest (say, $5) motivation; others might be similarly inclined.

**Comment by BrettplayMC** [comment]
I'd donate the above amount as well.

**Comment by SlimeDog** [comment]
We have created a private fork that adds PAPI support. If Minecrell would like a PR, or just the simple code changes, that can be arranged. (No, I will not share the fork; please don't ask.)

**Comment by Minecrell** [comment]
@SlimeDog I would be open to a PR, it depends a bit how it looks. I do not want a required dependency on PlaceholderAPI. But if it's integrated optionally somehow it would be fine.

**Comment by SlimeDog** [comment]
> I would be open to a PR

There you go (from mart-r). :)

**Comment by PlopHat** [comment]
Can't believe that after 4 years that i made this suggestion, it probabbly would happen. 😀

**Comment by SlimeDog** [comment]
@Minecrell ?
Please review the PR.

**Comment by SlimeDog** [comment]
> Can't believe that after 4 years that i made this suggestion, it probabbly would happen. 😀

You wished too soon. :(
We have switched to [ServerListMotd](https://www.spigotmc.org/resources/serverlistmotd.57851/), which has the necessary PAPI support.

**Comment by Minecrell** [comment]
> You wished too soon. :(

Well, is there any chance that the changes I suggested in the PR are going to be made? I spent quite a bit of time reviewing that properly and providing a clear path forward, but sadly there were never any changes made.

**Comment by SlimeDog** [comment]
The PR did what it needed to do. I hired a dev to make those changes, which were deemed inadequate. Since I have an alternative path forward, I am not inclined to spend more.

**Comment by RedstoneFuture** [comment]
I think this feature is the best way to support the most of exist feature requests with the [placeholder tag](https://github.com/Minecrell/ServerListPlus/issues?q=is%3Aissue+is%3Aopen+label%3Aplaceholder). Ideas like Nickname support or other are not the problem of ServerListPlugs, but if you add e.g. the PlaceholderAPI, the user can use all exist PAPI placeholders. :)
