### ISSUE TITLE
Server ping hover message not working?

### ISSUE THREAD

**Issue by mikexcat** [Minecrell/ServerListPlus#149]
Hey, I recently re-opened my server and installed this plugin. I did everything I (thought I) could and got nothing; the server's motd is working fine. The hover message, however, is showing no hope. I basically just filled in the blanks, went into console and typed /slp enable and then /slp reload. I have a Pastebin below, it'd be great if you helped. 
Thanks! 
Link - [http://pastebin.com/97kXQcKa](url)

**Comment by Minecrell** [comment]
Which platform are you running the plugin on? If you are using it on Spigot, do you have ProtocolLib installed?

**Comment by mikexcat** [comment]
I didn't have ProtocolLib installed. That was the issue, fixed now. Thanks! :+1:
