### ISSUE TITLE
Error/Bug

### ISSUE THREAD

**Issue by avsterbone** [Minecrell/ServerListPlus#150]
This spams my console:

http://pastebin.com/CgsuptQG

**Comment by Minecrell** [comment]
The error you pasted is not complete, it's missing the relevant part. Can you post the full log?

**Comment by avsterbone** [comment]
My bad, here you go

http://pastebin.com/FKBr8E2M

**Comment by Minecrell** [comment]
This is not the full log either unfortunately. I guess it does not print the full exception because it was happening so often. Can you upload the complete log file somewhere?

**Comment by avsterbone** [comment]
The full log contains sensitive information. Where can I send it so only your eyes will see it?

**Comment by Minecrell** [comment]
Feel free to PM me on SpigotMC or send me an E-Mail (check my GitHub profile for the address). However, I don't need the sensitive information - if you have the full log, check for the first time the error has happened and copy that one.

**Comment by avsterbone** [comment]
I have sent you a PM on Spigot

**Comment by Minecrell** [comment]
I assume updating has fixed your issue?

**Comment by avsterbone** [comment]
Yes, thank you
