### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by knightzmc** [Minecrell/ServerListPlus#151]
When starting my spigot 1.10 server, the plugin puts a whole bunch of errors into the console and doesn't load (it's red when doing /plugins and none of the /slp commands work)
Here's my console
http://pastebin.com/bVaHpSEK
Any help would be greatly appreciated :)

**Comment by Minecrell** [comment]
It seems like your player storage is corrupted. This can happen when the server crashes or is stopped while it is saving it. Try renaming/deleting the `PlayerCache.json` file in the plugin folder and restart the server.

**Comment by knightzmc** [comment]
That's fixed it - thank you!
