### ISSUE TITLE
Server list packet listener needs to be async (Bungeecord)

### ISSUE THREAD

**Issue by Fluxty** [Minecrell/ServerListPlus#154]
https://github.com/dmulloy2/ProtocolLib/issues/295#issuecomment-286466673

(This is an assumption, I should probably check myself before I rekt myself, but just trying to help and don't have much in the way of time)

**Comment by Minecrell** [comment]
Thank you for your report! [Fortunately, this is already the case for ServerListPlus.](https://github.com/Minecrell/ServerListPlus/blob/master/Bukkit/src/main/java/net/minecrell/serverlistplus/bukkit/handlers/ProtocolLibHandler.java#L55)
