### ISSUE TITLE
Problem Saving Config

### ISSUE THREAD

**Issue by goldfish2000** [Minecrell/ServerListPlus#155]
Whenever I edit the config to my liking and use /slp save it says that it saved sucessfully and everythiny is functional until i do /slp enable then it throws my configured version into the serverlistplus back-up config and rewrites an entirely new one.

**Comment by Minecrell** [comment]
You need to use `/slp reload` after editing the configuration file. `/slp save` is only designed to update the configuration with new options, and should be almost never used.

**Comment by goldfish2000** [comment]
Thx babe for responding so quick(no homo) lmfao. Ill go write u up a nice review on spigot. I was thinking it was something really simple i was doing wrong. And one more question, are all the Unicode characters in windows character map able to be used in UTF-8?

**Comment by Minecrell** [comment]
I think so yes. I guess you'll figure out when you get an error. ;)
