### ISSUE TITLE
Client outdated bug

### ISSUE THREAD

**Issue by AnHonorableHobo** [Minecrell/ServerListPlus#156]
My thing says client is outdated when it isnt? Image [here](https://gyazo.com/e48298e2924b7f734894a92c3fa1adcb)

Update: Fixed the "... and 1 more..." bug, idk why it appeared at all though, it'd be useful to know

**Comment by Minecrell** [comment]
Please read https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems carefully. It won't prevent players from joining, but using custom player slots will cause that to be displayed due to the way it works.
