### ISSUE TITLE
"Hover" not work after a few days

### ISSUE THREAD

**Issue by mat41997** [Minecrell/ServerListPlus#158]
config
https://gist.github.com/mat41997/370abc5510bd71d751d9b1e269de4c3a

i must restart server to this bug exsist
![2017-05-20 23_40_40-greenshot](https://cloud.githubusercontent.com/assets/5884000/26279488/f37ee13e-3db5-11e7-941b-6a4d8a6da84e.png)

i must use command "/slp disable" and "/slp enable" to fix "hover" : /
![2017-05-20 23_51_22-greenshot](https://cloud.githubusercontent.com/assets/5884000/26279551/4e6bdd12-3db7-11e7-8268-9183fbb64ef9.png)

timings
https://timings.aikar.co/?id=3389c6c0c4b74def86338d4947ac6f8f

torch
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

start command
```
screen -S mc -U -m java -server -Xms128M -Xmx3200M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -XX:UseSSE=3 -XX:SurvivorRatio=16 -XX:+UseCompressedOops -Xnoclassgc -XX:-UseFastEmptyMethods -XX:-UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -jar Torchpowered-1.11.2.jar
```

**Comment by Minecrell** [comment]
Might be an issue with Torch, I suggest you try it on a normal server using Paper or Spigot.
