### ISSUE TITLE
Unsupported server packet ID

### ISSUE THREAD

**Issue by SlimeDog** [Minecrell/ServerListPlus#160]
Spigot 1.12-pre5 latest
ProtocolLib 4.3.0-b367
ServerListPlus 3.4.7

Warning on start-up, and hover content does not display.

> [16:03:06] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [ServerListPlus] Unsupported server packet ID in current Minecraft version: OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]
[16:03:06] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] [ServerListPlus] Unsupported server packet ID in current Minecraft version: OUT_SERVER_INFO[class=PacketStatusOutServerInfo, id=0]

No issue with ProtocolLib 4.3.0-b364 and previous.

**Comment by Minecrell** [comment]
Confirmed.

**Comment by Minecrell** [comment]
Looks like a ProtocolLib issue to be honest. 

@dmulloy2 Any ideas? I'm aware I'm still using the deprecated `OUT_SERVER_INFO` but since that was just a rename of the field it should still work correctly in newer Minecraft versions.

**Comment by dmulloy2** [comment]
Should be fixed in the latest build. I've been reworking some stuff with packet types.

**Comment by Minecrell** [comment]
@dmulloy2 Thanks, it works fine now!
