### ISSUE TITLE
How can I set custom server version?

### ISSUE THREAD

**Issue by symvizan** [Minecrell/ServerListPlus#164]
I want to set a custom server version there was a feature in this plugin for sure but I can't find it on the Wiki on how to configure.

I am looking for an option that changes my 'Spigot 1.12' server version to a custom one, and not the custom players slots thing.

Thank you.

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/wiki/Status-Configuration#outdated-version

**Comment by symvizan** [comment]
Thank you.
