### ISSUE TITLE
Add variables for banned clients

### ISSUE THREAD

**Issue by ApertureDevelopment** [Minecrell/ServerListPlus#166]
Hey I wanted to request an feature,

If someone get banned you can set static Textes like "&4You were banned!" how about adding usable variables like:
- %reason%
- %unbandate%
- %banningstaff%
- %remainingtime%
This would ( in my eyes ) be an better way to tell players that, and why they are banned and who banned them. then messages like:
 - '&c%player% &4got banned from the server. You get unbanned at: %unbandate%'
- '&4Reason: &e%reason% &4Duration: &e%remainingtime% &4Banning Staff: &e%banningstaff%'

would be possible and would give the server a more professional look.

Thanks for reading,
~Captain1242

**Comment by captain1242** [comment]
Also compatibility to all banning plugins :3

**Comment by captain1242** [comment]
Ok I am trying to write it on my own, but I don't know how to again override this function: 

@Override
public boolean isBanned(PlayerIdentity playerIdentity) {
    return getServer().getBanList(BanList.Type.NAME).isBanned(playerIdentity.getName());
}

**Comment by BrainStone** [comment]
You can try this file [ServerListPlus-3.4.9-SNAPSHOT-Universal.jar.zip](https://github.com/Minecrell/ServerListPlus/files/1821010/ServerListPlus-3.4.9-SNAPSHOT-Universal.jar.zip) (unpack it first) and see if it works. For me it's working.

**Comment by captain1242** [comment]
What are the new Variables? The Wiki is incomplete
