### ISSUE TITLE
Empty hover shows a blank box instead of no box

### ISSUE THREAD

**Issue by jonthesquirrel** [Minecrell/ServerListPlus#175]
![image](https://user-images.githubusercontent.com/6022168/31873069-71994dd0-b786-11e7-8608-1478498a6589.png)
When there are no players online or there is only empty space in the hover configuration, it shows a blank hover box one space wide. I'd rather it not show at all when it's empty, because that blank box is a little awkward.

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/issues/113
