### ISSUE TITLE
support to redis bungee

### ISSUE THREAD

**Issue by friishon** [Minecrell/ServerListPlus#176]
can you add support to redis bungee??
i have problems with players name, with 0 players, it show the name of the last player

**Comment by Minecrell** [comment]
Could you clarify your problem? What exactly is broken?

**Comment by friishon** [comment]
user apear in welcome, i have load balance, and apear the last name, i think that happends because of the load balancer, but can be solve? or only if i remove the placeholder?
![1](https://user-images.githubusercontent.com/19889173/32138187-c48abf4a-bc2e-11e7-9958-95ff29fba8a9.png)

![2](https://user-images.githubusercontent.com/19889173/32138188-c4a3ae24-bc2e-11e7-8ea5-f35b5edfd6de.png)

**Comment by Minecrell** [comment]
Well, it appears like your load balancer doesn't pass the real player IPs to ServerListPlus. Depending on your setup, I guess it's either not supported or not configured properly. ServerListPlus can't track player names correctly without the real IP of the player.

**Comment by friishon** [comment]
I saw, maybe i have to make better the load balancer or something, i will check, i use haproxy to make the load balancer

**Comment by Minecrell** [comment]
I don't have any experience with haproxy, but it seems BungeeCord recently added something that might help: https://github.com/SpigotMC/BungeeCord/commit/daac8d85e20baed2ee0107ee637d0e82af8b2cd1

Make sure you set `proxy_protocol` to `true` in your BungeeCord configuration...

**Comment by friishon** [comment]
Oh, thanks, i will try it

**Comment by friishon** [comment]
Thanks for the help, i fixed, and now works fine
