### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by GMatrixGames** [Minecrell/ServerListPlus#180]
Hello, I am having a console error when I go to load the plugin. Can you help?

[ServerListPlus.zip](https://github.com/Minecrell/ServerListPlus/files/1452056/ServerListPlus.zip)

**Comment by Minecrell** [comment]
The indentation is wrong on one line. All you need to do, is add a single space before it.

See https://gist.github.com/Minecrell/8663b82962c1a1efa60c394cb05a84c6/revisions#diff-b67b8c46775020254e42fba73b4d0755
