### ISSUE TITLE
Metrics are not very useful nowadays

### ISSUE THREAD

**Issue by DoNotSpamPls** [Minecrell/ServerListPlus#181]
https://mcstats.org is a mixed bag when it comes to stability. Sometimes it works, sometimes it doesn't, sometimes it loads for 3 minutes. I think MCStats should be changed with a working alternative

![Image from today](https://bitcoin.is-serious.business/410628.png)

**Comment by Minecrell** [comment]
Agreed, however I'm not aware of any appropriate alternative. I'd switch to BStats, but it's less than ideal considering it doesn't support statistic merged on one page (see https://github.com/BtoBastian/bStats/issues/21).

On the other hand, considering I support 5 different platforms, I care only about the merged statistics. Therefore adding the plugin to BStats several times wouldn't be helpful at all. As it stands, MCStats is still the only service that will let me look at merged statistic for all platforms.

I'm considering removing the statistics entirely for SLP 4.0. Within the last months, I was still able to look at the [SLP statistic page](http://mcstats.org/plugin/ServerListPlus) properly with a few refreshs every now and then, but I agree that it's not something you should continue to build on.

**Comment by spannerman79** [comment]
Seems that mcstats are suffering major downtimes
SLP is constantly spamming `[ServerListPlus] Failed to submit plugin statistics: java.net.ConnectException: Connection timed out (Connection timed out)`

I'll have to get a plugin just to remove/filter out SLP messages like that

`ServerListPlus v3.4.8 (BungeeCord)`

**Comment by Minecrell** [comment]
You can disable in SLP configuration: Set `Stats` to false, and it will stop trying to reach MCStats.

**Comment by Minecrell** [comment]
Console spam is fixed in https://github.com/Minecrell/ServerListPlus/commit/8060d9ec779e93037a649174d2266916d95c4156, I will keep MCStats for 3.x and investigate alternative solutions for 4.0.

**Comment by sgdc3** [comment]
bstats for president

**Comment by Minecrell** [comment]
My main concern with BStats mentioned in my first comment (https://github.com/Minecrell/ServerListPlus/issues/181#issuecomment-343243957) remains. I don't need separated stats (at all), I need stats over all platforms. As far as I know, BStats still doesn't provide anything to facilitate this.

I don't really need these statistics, so at the moment it seems more likely I will remove them entirely. And yes, the future of SLP 4.0 is uncertain, mostly due to lack of time but also motivation. :/

**Comment by Minecrell** [comment]
Removed in https://github.com/Minecrell/ServerListPlus/pull/340
