### ISSUE TITLE
When is the 4.0 version ? :c

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#182]
When is the 4.0 version ? :c

**Comment by Minecrell** [comment]
When it's ready.

**Comment by TheIntelloBox** [comment]
I know but have you an Estimate date ?

**Comment by Minecrell** [comment]
No, sorry.

**Comment by EmanYm** [comment]
Three weeks from next Tuesday, or when the version numbers call for it.  Considering this is only on a stable build number of 3.4.8, it could be a very long time.
Keep in mind that snapshot and beta builds are almost never good to use on a production server.
