### ISSUE TITLE
Problem with UUID

### ISSUE THREAD

**Issue by Yub0** [Minecrell/ServerListPlus#186]
Hello,

I've tried to add Favicon with url and I've writed this in my configuration

`Favicon:
    URLs:
    - https://visage.surgeplay.com/bust/64/%_uuid_%`

Is showing a bust, but a default skin. The variable uuid doesn't work I think.

![screenshot_1](https://user-images.githubusercontent.com/7883422/34441617-2f34abb2-ecbd-11e7-83d7-c6824033399e.png)

Thanks

**Comment by RageYT** [comment]
+1, I am also having this issue, not sure on the fix since it wasn't shared.

**Comment by Minecrell** [comment]
Make sure your server is running in online mode.
