### ISSUE TITLE
MaxBans support.

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#188]
Hi,

I banned a player but with the MOTD, it's not said : "You're banned" whereas I have put it in the config.
I use MaxBans.

**Comment by BrainStone** [comment]
@TheIntelloBox could you link the plugin you are referring to?

I'm not sure why excat one you mean, as I found several.

**Comment by TheIntelloBox** [comment]
https://dev.bukkit.org/projects/maxbans/files/2421382

**Comment by BrainStone** [comment]
Would you mind trying this file? (Unpack it first)
[ServerListPlus-3.4.9-SNAPSHOT-Universal.jar.zip](https://github.com/Minecrell/ServerListPlus/files/1821010/ServerListPlus-3.4.9-SNAPSHOT-Universal.jar.zip)

**Comment by TheIntelloBox** [comment]
Fantastic, no error, thanks BrainStone ! :D
