### ISSUE TITLE
Server Player Count not Working

### ISSUE THREAD

**Issue by Sunboyz21** [Minecrell/ServerListPlus#193]
So I'm using this config: https://pastebin.com/4xin6Yxr
On BungeeCord 1.8 with 4 1.7-1.8 Servers
Screenshot: https://imgur.com/a/H2RCr
However, when I go into the Multiplayer tab, Practice, Hub, & Kit all have ??? and only HCF has 0/250 even though it's not even enabled. [Screenshot: https://imgur.com/a/K95S0]
Please help!
~~Chief

**Comment by Minecrell** [comment]
What does "even though it's [HCF] not even enabled" mean? "???" happens if there is no such server in your BungeeCord config. Can you also post that one?

**Comment by Minecrell** [comment]
Closing for now, please comment here if you still need help.

**Comment by Sunboyz21** [comment]
Ok, so I had fixed the issue before, but now it's back.
I have a different categories of gamemodes, Casual and Comp
So each server is named accordingly, for example:
(Cas)_SW
(Comp)_HCF
All servers are in my bungeecord config and contain no spaces, yet when i plug them into my serverlistsplus config (https://pastebin.com/tH9FxGzn), this is what the playercount looks like (https://imgur.com/a/ZlMqJ)!
Please help,
~~Sunboyz

**Comment by Minecrell** [comment]
The problem are the parentheses in the server names. Are they really necessary? The placeholder doesn't support them right now.

**Comment by Sunboyz21** [comment]
Ok, so if I do Comp_Hub instead of (Comp)_Hub it'll work? Or do I have to remove the underscores too?
Thanks m8!
~~Sunboyz

**Comment by Minecrell** [comment]
Underscores should be fine.

**Comment by Sunboyz21** [comment]
Ok, thanks! The issue is solved :)
~~Sunboyz
