### ISSUE TITLE
ServerListPlus Doesnt work

### ISSUE THREAD

**Issue by ItzBrooksFTW** [Minecrell/ServerListPlus#194]
I installed it on my bungeecord proxy, i configured everything but it doesnt work, i know i need to  execute command /serverlistplus enable in console but i cant (server.pro hosting) please help

**Comment by Minecrell** [comment]
You can either run it from the BungeeCord console or ingame, after granting yourself the permission in the BungeeCord configuration.

**Comment by ItzBrooksFTW** [comment]
when i go rlp enable on bungeecord proxy console it doesnt work it says that that command doesnt exist something like that

**Comment by Minecrell** [comment]
The command is `/slp enable` or `/serverlistplus enable`, not `/rlp enable`.

**Comment by ItzBrooksFTW** [comment]
i cant execute any command in my proxy console

**Comment by Minecrell** [comment]
Then give yourself the permission and run it ingame.

**Comment by ItzSheldor** [comment]
I have the same Problem even if I gave me the perm directly.

**Comment by Minecrell** [comment]
Please post your BungeeCord configuration and the BungeeCord log, after you have attempted to run the command.

**Comment by ItzBrooksFTW** [comment]
Config:

ip_forward: true
network_compression_threshold: 256
stats: a3209a19-6449-43e8-9655-e504323e857b
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: ''
    address: 37.187.158.155:40507
    restricted: false
  Factions:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 149.202.92.237:40474
    restricted: false
  SkyPvP:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 149.202.70.191:40923
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25577
  motd: ''
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 149.202.92.161:41869
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 100
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: false
log_commands: false
disabled_commands:
- find
- server
- disabledcommandhere
connection_throttle: 4000

**Comment by Minecrell** [comment]
Please post them on https://gist.github.com/ and copy the link here. Also, please post the full log, not just the command execution.

**Comment by ItzSheldor** [comment]
https://gist.github.com/ItzSheldor/9022e31b46b791f917d73705fd3827ed

**Comment by Minecrell** [comment]
You need to add `serverlistplus.admin` to the admin permission list: https://gist.github.com/ItzSheldor/9022e31b46b791f917d73705fd3827ed#file-config-yml-L8-L12
