### ISSUE TITLE
Where is the Favicons section?

### ISSUE THREAD

**Issue by redXpanda** [Minecrell/ServerListPlus#207]
I just found Favicon section in config/ServerListPlus/~.yml.
And I write 
Favicon:
    Folders:
    - icons
it doesn't work.

**Comment by Minecrell** [comment]
Take a look at the example configuration: https://github.com/Minecrell/ServerListPlus/wiki/Examples

**Comment by redXpanda** [comment]
That's good. Thank you sir.
