### ISSUE TITLE
I add this plugin in mods folder, and use the statusprotocol 3.0 too, but this plugin doesn't work.

### ISSUE THREAD

**Issue by Moeblack** [Minecrell/ServerListPlus#208]
my server is forge-1.12.2-14.23.3.2655 with spongeforge-1.12.2-2655-7.1.0-beta-3070. the plugins loaded but command slp is not registered.
![tim 20180515100814](https://user-images.githubusercontent.com/28835093/40032719-e8e3e426-5827-11e8-8aad-df16ef1a257c.jpg)

**Comment by PrimalMew** [comment]
I'm having the same issue.

**Comment by Minecrell** [comment]
"Please post the full log."
