### ISSUE TITLE
Request (not about SLP)

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#209]
Hi,

Sorry to post that here, but there is no repository for SimpleUC on your github.
I have a question: Could you update SimpleUC to 1.13 when the version will be released ?

Thanks ! :D

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/TerminalConsoleAppender/issues/1

**Comment by TheIntelloBox** [comment]
Sorry, and gg for your memory. xD
