### ISSUE TITLE
Errors on errors and no help from protocollib team.

### ISSUE THREAD

**Issue by CyrusMusic101** [Minecrell/ServerListPlus#213]
https://pastebin.com/v4WnF6qt my server is 1.8 spigot. Ive tried every single combination possible of protocollib on my server and slp but none work. 0 idea why. It breaks with every single frickin plugin. They ignored me so im hoping you can help me.

**Comment by Minecrell** [comment]
Have you tried ProtocolLib 3.6.5? https://www.spigotmc.org/resources/protocollib.1997/download?version=69182

Also make sure you use the 1.8 version of SLP: https://github.com/Minecrell/ServerListPlus/releases/download/3.4.8/ServerListPlus-3.4.8-Bukkit-1.8.jar

If that doesn't help I'm afraid I can't really help you much either. Consider upgrading to newer MC versions.
