### ISSUE TITLE
Developer Builds CI Page Offline

### ISSUE THREAD

**Issue by CDAGaming** [Minecrell/ServerListPlus#215]
Going to https://ci.minecrell.net/job/ServerListPlus/ results in an error (On Chrome) stating it cannot be found.

**Comment by Minecrell** [comment]
See https://www.spigotmc.org/threads/serverlistplus.7371/page-77#post-3049265

**Comment by sgdc3** [comment]
@Minecrell if you want i can create an user on my public build server, i have a per folder based permission system and i already share it with other dev teams. https://ci.codemc.org/ If you are interested let me know.

**Comment by Minecrell** [comment]
@sgdc3 Thanks, I appreciate the offer! But I think I'd rather setup something using Travis or similar, never really liked Jenkins very much. Not sure yet, I'll let you know if I change my mind. :)

**Comment by sgdc3** [comment]
@Minecrell in the meantime: https://ci.codemc.org/job/Minecrell/job/ServerListPlus/ ;) If you want i can also provide the artifact via maven repository.

**Comment by sgdc3** [comment]
If you want to edit/delete it just login, the authentications works via github oauth ;)
