### ISSUE TITLE
Spam Error on join,

### ISSUE THREAD

**Issue by Duck1D** [Minecrell/ServerListPlus#216]
So I get this spam whenever a player joins, but I don't know what is causing this
[https://pastebin.com/y9FtGq2n](url)

Here is my config:
https://pastebin.com/e7MmvnJS

**Comment by Minecrell** [comment]
Can you try to set `Samples.Multiple` back to `false`? (Line 120)

**Comment by Duck1D** [comment]
I will try, when I can get on later.
