### ISSUE TITLE
Player Slot doesn't work

### ISSUE THREAD

**Issue by JoshHeng** [Minecrell/ServerListPlus#217]
I have this in my config, in both the default and personalized section:  
Players:
    Max: 
    - 100
    Slots:
    - '&ePlease use 1.12.2 only!'

But it doesn't seem to work as I get the default error of 'Spigot 1.12.2'. 
How do I fix this?

Also the personalization part doesn't seem to work - are there certain criteria for this to work or will it just always show the default section?

Thanks

**Comment by Minecrell** [comment]
Can you post your full configuration on https://gist.github.com and copy the link here? There might be a syntax mistake somewhere.

> Also the personalization part doesn't seem to work - are there certain criteria for this to work or will it just always show the default section?

It works by tracking the IP addresses of the players who connected to your server at least once (after ServerListPlus was installed). That means you need to join your server once before it gets activated for the next time.

**Comment by JoshHeng** [comment]
[https://gist.github.com/JoshHeng/741e74941bac43c8bdd12bf8f820674f](https://gist.github.com/JoshHeng/741e74941bac43c8bdd12bf8f820674f)
Thanks

**Comment by Minecrell** [comment]
What exactly are you trying to do with the Player Slot feature? It sounds like you're trying to change the displayed version when outdated Minecraft versions ping your server.

Player slots are applied when players with the correct version ping your server (i.e. only for 1.12.2 clients). All others get the Minecraft version (`Spigot 1.12.2` in your case). If you'd like to change that version, use the "outdated version" feature: https://github.com/Minecrell/ServerListPlus/wiki/Status-Configuration#outdated-version

**Comment by JoshHeng** [comment]
Oh, ok - thanks
