### ISSUE TITLE
Help Reloaded Bungee Now Its Not Working

### ISSUE THREAD

**Issue by Rxlizard** [Minecrell/ServerListPlus#218]
pls help i was messing with the config got it right here i wanted it save it then i updated viaversion to 1.4.1 reloaded bungee and it was broken so i was like damn took out viaversion made it back to 1.4.0 and it still dose not work wtf is going on no error message in console

**Comment by Minecrell** [comment]
How is SLP related to ViaVersion?

**Comment by Rxlizard** [comment]
Idk maybe it did im just saying the events leading up to the problem to help fix the problem.

**Comment by Minecrell** [comment]
So what exactly is the problem...?

**Comment by Rxlizard** [comment]
I had SLP working everything was good I did the config the way I wanted to 100% working. I later did some updates mention above restarted bungee now it doesn't work it went back to the server description i had before the plugin was installed. It's in the plugin folder just doesn't work.

**Comment by Minecrell** [comment]
Can you post:

- The full server log (from BungeeCord)
- Your SLP configuration

**Comment by Rxlizard** [comment]
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.8 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
  - |-
    &6Welcome To &fNimbus&bMC&6. Lots of &cCustom &6Plugins.
    &eSkyblock Factions Survival Creative.
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online% &aplayers on.
Personalized:
  Description:
  - |-
    &6Welcome Back &a%player% &6To &fNimbus&bMC&6.
    &6Currently &e%online% &6Players Online!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online% &aplayers on. 

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: false
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

22.07 13:05:50 [Multicraft] Starting server!
22.07 13:05:50 [Multicraft] Loaded config for "Mod: BungeeCord"
22.07 13:05:50 [Multicraft] Updating eula.txt file
22.07 13:05:50 [Server] INFO *** Warning, this build is outdated ***
22.07 13:05:50 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
22.07 13:05:50 [Server] INFO *** You will get NO support regarding this build ***
22.07 13:05:50 [Server] INFO *** Server will start in 10 seconds ***
22.07 13:06:00 [Server] INFO Using mbed TLS based native cipher.
22.07 13:06:00 [Server] INFO Using zlib based native compressor.
22.07 13:06:00 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:730715e:1321
22.07 13:06:00 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
22.07 13:06:00 [Server] INFO Epoll is working, utilising it!
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
22.07 13:06:00 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:730715e:1321 by SpigotMC
22.07 13:06:00 [Server] INFO Loaded plugin LuckPerms version 4.2.37 by Luck
22.07 13:06:00 [Server] WARNING Error enabling plugin BungeePortals
22.07 13:06:00 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
22.07 13:06:00 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
22.07 13:06:01 [Multicraft] Skipped 120 lines due to rate limit (30/s)
22.07 13:06:01 [Server] INFO [BuycraftX] Validating your server key...
22.07 13:06:01 [Server] WARNING [ViaVersion] There is a newer version available: 1.4.1, you're on: 1.4.0
22.07 13:06:02 [Server] INFO Enabled plugin BuycraftX version 10.6.2 by Buycraft
22.07 13:06:02 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:730715e:1321 by SpigotMC
22.07 13:06:02 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:730715e:1321 by SpigotMC
22.07 13:06:02 [Server] INFO Enabled plugin ViaBackwards version 2.3.1 by Matsv
22.07 13:06:02 [Server] INFO [BungeeTabListPlus] Starting UpdateChecker Task
22.07 13:06:02 [Server] INFO [BungeeTabListPlus] Loading default.yml
22.07 13:06:02 [Server] INFO Enabled plugin BungeeTabListPlus version 2.8.4 by CodeCrafter47
22.07 13:06:02 [Server] Startup Listening on /131.153.31.74:25565
22.07 13:06:03 [Server] INFO [BuycraftX] Fetching all due players...
22.07 13:06:04 [Server] INFO [BuycraftX] Fetched due players (0 found).
22.07 13:06:51 [Server] INFO glist
22.07 13:06:51 [Server] INFO [Creative] (0): 
22.07 13:06:51 [Server] INFO [Factions] (0): 
22.07 13:06:51 [Server] INFO [Hub] (0): 
22.07 13:06:51 [Server] INFO [Survival] (0): 
22.07 13:06:51 [Server] INFO [SkyBlock] (0): 
22.07 13:06:51 [Server] INFO Total players online: 0

**Comment by Rxlizard** [comment]
#      _____                     __    _     _   _____ _
#     |   __|___ ___ _ _ ___ ___|  |  |_|___| |_|  _  | |_ _ ___
#     |__   | -_|  _| | | -_|  _|  |__| |_ -|  _|   __| | | |_ -|
#     |_____|___|_|  \_/|___|_| |_____|_|___|_| |__|  |_|___|___|
# 
# ServerListPlus v3.4.8 - http://git.io/slp

# More information is available in the Wiki: http://git.io/slp-wiki


# This is the section where you can customize your server status ping!
#  - Default is the section for the status used when the player name is unknown.
#    Personalized is used if the client has already joined the server once.
#    Use %player% as placeholder for the player's name.
# 
# Features:
#  - Description (MotD): A short status message for your server, max. 2 lines.
#  - Players:
#    - Hover: The player hover message that is displayed if you hover the player count.
#    - Slots: Custom player slot formatting, see http://git.io/slp-slots
#  - Favicon:
#    - Use multiple server icons or the player's head as favicon, see http://git.io/oMhJlg
#    - Possible favicon sources: Files, Folders, URLs, Heads, Helms, Encoded
# 
#  More features are explained in the Wiki: http://git.io/slp-config
# 
# Usage:
#  - Add multiple entries for random messages.
#  - Save the file with valid UTF-8 encoding for special characters.
#  - Available placeholders:
#    - Player name: %player%
#    - Player count: %online%, %max%, %online@server% %online@world%
#    - Random online player name: %random_player%
--- !Status
Default:
  Description:
  - |-
    &6Welcome To &fNimbus&bMC&6. Lots of &cCustom &6Plugins.
    &eSkyblock Factions Survival Creative.
  Players:
    Hover:
    - |-
      &aWelcome to &lA Minecraft Server&a!
      &aCurrently &e&l%online% &aplayers on.
Personalized:
  Description:
  - |-
    &6Welcome Back &a%player% &6To &fNimbus&bMC&6.
    &6Currently &e%online% &6Players Online!
  Players:
    Hover:
    - |-
      &aWelcome back, &l%player%&a!
      &aCurrently &e&l%online% &aplayers on. 

# Stats: Enable/disable sending plugin statistics.
# PlayerTracking: Enable/disable tracking of player names to their IP-Addresses.
#   - Persistence can be disabled with the toggle in the Storage section.
# Samples: Toggle using multiple player infos for the player hover message.
#     May prevent the annoying ... and x more ... message for bigger servers
#     DynamicPlayers is special and aligns the number with the number of
#     random players used in placeholders.
# Unknown: Placeholder replacement if the real value is unknown.
# Favicon: Options for the creation / downloading of favicons:
#  - RecursiveFolderSearch: Also search for favicons in sub directories.
#  - SkinSource: The URL to get the Minecraft Skins from. (%s -> player name)
#  - ResizeStrategy: The strategy used to resize too small or too big favicons.
#      NONE (keep them as is, will probably fail), SCALE (scale them to the correct size)
--- !Plugin
Stats: true
PlayerTracking:
  Enabled: true
  Storage: !JSONStorage
    Enabled: true
    SaveDelay: 5m
Samples:
  Multiple: false
  DynamicPlayers: false
Unknown:
  PlayerName: player
  PlayerCount: ???
  Date: ???
Favicon:
  Timeout: 10s
  RecursiveFolderSearch: false
  ResizeStrategy: SCALE

**Comment by Rxlizard** [comment]
wft is wrong with github
   

https://hastebin.com/oqerisijif.shell

**Comment by Minecrell** [comment]
Your log doesn't say anything about ServerListPlus: It was either not loaded or the log is incomplete. Can you post the `proxy.log.0` file instead?

**Comment by Rxlizard** [comment]
yea
https://hastebin.com/iwakaqomoh.sql

**Comment by Rxlizard** [comment]
if we can get this fixed ill gladly donate

**Comment by Rxlizard** [comment]
[Bungee.zip](https://github.com/Minecrell/ServerListPlus/files/2217532/Bungee.zip)

**Comment by Minecrell** [comment]
@Rxlizard SLP isn't even loaded. Are you sure it's in your plugins folder?

**Comment by Rxlizard** [comment]
Yes

**Comment by Minecrell** [comment]
Have you tried running `slp enable` again in the console?

**Comment by Rxlizard** [comment]
Not in console im at work will do when i get home

**Comment by Rxlizard** [comment]
i fixed it thanks for all your help the jar literally got corrupted or something just threw a fresh jar in and del the old one. donate button somewhere or paypal email

**Comment by Minecrell** [comment]
@Rxlizard Glad it's working now. Right now I don't accept donations. If you'd like to say thanks, maybe leave a nice review on https://www.spigotmc.org/resources/serverlistplus.241/reviews?
