### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/ServerListPlus#221]
Hi,

Does SLP support 1.13 ?

**Comment by Minecrell** [comment]
Yes. ServerListPlus v3.4.8 works fine on 1.12

If you use Spigot, you need the latest ProtocolLib development build from http://ci.dmulloy2.net/job/ProtocolLib/.

**Comment by TheIntelloBox** [comment]
Thanks Minecrell. :)
