### ISSUE TITLE
Player count returns -1

### ISSUE THREAD

**Issue by Artuto** [Minecrell/ServerListPlus#223]
So, when a moderator or admin enters in vanish mode using Premium/Simple Vanish the member count (the one that appears alongside the ping) shows -1

Could you please fix this ASAP? this way players can know if a staff is on vanish.

**Comment by Minecrell** [comment]
SLP generally doesn't modify the online player count, this is probably not caused by this plugin. Might be an issue with another plugin or your server implementation.

**Comment by Artuto** [comment]
This does not happens with SLP uninstalled.

**Comment by Minecrell** [comment]
Could you share more about your environment? Server version? SLP version?

**Comment by Artuto** [comment]
Waterfall 1.13 - SLP 3.5.0

**Comment by Minecrell** [comment]
Are these plugins installed on the proxy too? How does the proxy know which players are vanished?

**Comment by Artuto** [comment]
PremiumVanish is installed in the Proxy, yes

**Comment by Minecrell** [comment]
Well, I'm afraid I'm unable to help you here for the following reasons:

- SLP does not change the **online** player count, so if anything it must be another plugin that does this based on something SLP is doing (e.g. the player sample/hover list).
- PremiumVanish is a proprietary plugin, so I am unable to reproduce the issue or even just take a look at the source code to find potential reasons for your problem.

You may have more luck contacting the developer of PremiumVanish. SLP is open-source and free so they can easily reproduce and investigate its source code. Sorry :(
