### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by augesrob** [Minecrell/ServerListPlus#224]
https://i.gyazo.com/6b6a2a40cfbbca23449c91eff628be62.png

**Issue:** 
1.13 Server Status Shows Old
FavIcon Doesn't Seem To Work

**Version**
Jenkins Build 431
ServerListPlus version 3.5.0-SNAPSHOT

**Config (Regenerated from nothing)**
https://hastebin.com/kuvinanita.shell

**Comment by Minecrell** [comment]
Can you post a full copy of your server log?

**Comment by Minecrell** [comment]
Closing this for now. Please post a full copy of the log if you need help. Otherwise, see https://github.com/Minecrell/ServerListPlus/issues/221
