### ISSUE TITLE
1.13 client error

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Minecrell/ServerListPlus#226]
when 1.13 clients try to join my 1.12.2 server, the motd looks like this
![glitch](https://user-images.githubusercontent.com/37032797/44885601-93c3c800-ac76-11e8-9d8c-d586d7561c4b.gif)
It's fine on 1.12.2 and lower versions, I believe this exists because I have multiple possible motd's that can be sent set with this plugin.

**Comment by Minecrell** [comment]
That looks like a client bug, there is never more than one motd sent. It looks like you use the obfuscated formatting code `&k`? That might be causing issues here.
