### ISSUE TITLE
Favicon fix for 1.13+

### ISSUE THREAD

**Issue by Cybermaxke** [Minecrell/ServerListPlus#236]
Since 1.13, it's no longer supported to use new line characters inside encoded favicons.

A simple fix is to modify the method at the following line: https://github.com/Minecrell/ServerListPlus/blob/master/Server/src/main/java/net/minecrell/serverlistplus/server/status/Favicon.java#L48
From
`ByteBuf base64 = Base64.encode(buf);`
to
`ByteBuf base64 = Base64.encode(buf, false);`

**Comment by Minecrell** [comment]
Thanks for the note! Would you mind opening a PR with your proposed fix?
