### ISSUE TITLE
Litebans support revisited

### ISSUE THREAD

**Issue by PsychoLynx** [Minecrell/ServerListPlus#239]
Howdy!

I took the initiative to go ask the creator of LiteBans to add support for ServerListPlus. This is the response I got "I cannot add support for ServerListPlus unless it guarantees that all ban checks are always executed async, not on the main server thread. As it uses sync events ServerListPingEvent/PaperServerListPingEvent I don't think it will be possible." (https://gitlab.com/ruany/litebans-php/issues/43)

Not sure if there's anything you can do about the events, but I thought I'd at least let you know. Cheers.

**Comment by untuned** [comment]
I second this, please add Litebans support.

**Comment by Minecrell** [comment]
Server status pings are executed asynchronously (i.e. not on the main thread) on all supported platforms. This also applies to `ServerListPingEvent` and `PaperServerListPingEvent`. Therefore this should not prevent implementing support for SLP in LiteBans.

My main argument against supporting LiteBans directly in SLP still applies. I strongly believe in open-source, and do not want to support any proprietary plugin directly in SLP. (Note: To make this absolutely clear: I'm strictly talking about open-source, not "premium".)

However, I'm not aware of any reason that should prevent to make LiteBans working with SLP with one of the following ways:

- Support for ServerListPlus in LiteBans
- Create a "bridge" plugin that depends on both SLP and LiteBans, and implements the SLP API on top of LiteBans

**Comment by untuned** [comment]
Thanks for the feedback, I made an issue on the GitLab to see if something can be done:
https://gitlab.com/ruany/LiteBans/issues/76
