### ISSUE TITLE
API to get motd of a server

### ISSUE THREAD

**Issue by Sir-Will** [Minecrell/ServerListPlus#242]
Is there any way to get the motd of a server via ServerListPlus without going the path of pinging the server?

**Comment by Sir-Will** [comment]
Right now it's only running in BungeeCord but I want to get the motd of each server on a spigot server.

**Comment by Minecrell** [comment]
ServerListPlus will usually run only on your proxy server. Everywhere else does not really make sense, because players will never ping backend servers directly.

**Comment by Sir-Will** [comment]
Yes but isn't there already a bridge between the bungee and spigot version for placeholders?

**Comment by Minecrell** [comment]
No, SLP does not currently provide such placeholders.

**Comment by Sir-Will** [comment]
Oh I think I mixed it up with BungeeTabListPlus then. Would be too much work without an existing bridge I guess.

**Comment by Minecrell** [comment]
In my opinion, a bridge like that ought to be handled by other plugins. It makes sense for plugins that have to run on both proxy and backend servers, but SLP really has no use at all on the backend servers.
