### ISSUE TITLE
IP tracking with same IP players

### ISSUE THREAD

**Issue by hamcoremusic** [Minecrell/ServerListPlus#249]
My brother and I both play on the same public IP. Should I keep IP tracking on or if I turn it off, will it just display whatever name is detected in the client?

**Comment by Minecrell** [comment]
You can keep it on if you don't mind seeing your brother's name occasionally. It will display the name of the last player that joined using the IP.

**Comment by hamcoremusic** [comment]
Will it break if I turn it off? Just curious.

**Comment by Minecrell** [comment]
If you turn it off, then no new IP address will be tracked. This means that `%player%` etc will be replaced incorrectly / with `unknown`. But nothing will break if you are not using the placeholder.
