### ISSUE TITLE
%randomplayers,#% placeholder bug

### ISSUE THREAD

**Issue by MidnightSugar** [Minecrell/ServerListPlus#254]
The placeholder %randomplayers% does not display properly if you have it set to list multiple players.

Say you have 3 players online, and have it set to display 9 players in a list. It will display like this:

Player 1
Player 2
Player 3
... and 2 more ...

So basically it is not taking into account the numbers of players being listed. It just takes the total number of players and subtracts 1.

**Comment by Minecrell** [comment]
Yeah, that's how it works by default.

This is what the `Samples.Multiple` and `DynamicPlayers` option is for. If you set both to true it should handle it correctly.
