### ISSUE TITLE
Added to Spigot 1.8.9 server and it doesnt seem to work

### ISSUE THREAD

**Issue by Lxk3y** [Minecrell/ServerListPlus#267]
This really isnt a helpful issue im aware, but i didnt know where else to post it. Ive added it to server, it made the files, /plugins shows it green and running, but my MOTD is just the default "A Minecraft Server". I am using Hawn Lobby Plugin which does change the MOTD however ive disabled it on the config, hence the default one is now being displayed.  Any ideas? Thanks

**Comment by Olly32** [comment]
/slp enable
bruh read the desciption before opening an issue
