### ISSUE TITLE
YAML syntax error

### ISSUE THREAD

**Issue by Bublelift** [Minecrell/ServerListPlus#274]
So here I am, doing Ctrl+C and Ctrl+V cus somebody can't do it here :))))))
[config_for_dummies.txt](https://github.com/Minecrell/ServerListPlus/files/4147911/config_for_dummies.txt)
Here's the error log
[error.txt](https://github.com/Minecrell/ServerListPlus/files/4147924/error.txt)
I literally cannot even change anything in the config on my server site in FTP, because it doesn't allow me to save the fille: YAML syntax error!
The following line is highlighted as causing the error:
--- !Plugin

**Comment by Minecrell** [comment]
Replied on the other issue.
