### ISSUE TITLE
Plugin API to inform SLP that a player is banned

### ISSUE THREAD

**Issue by BrainStone** [Minecrell/ServerListPlus#275]
Hi there.   
I'd like to be able to inform SLP that a player is banned when pinging the server. So that you don't have to add the support yourself.

**Comment by Minecrell** [comment]
You added support for the Ban API in https://github.com/Minecrell/ServerListPlus/pull/201 and documented it here: https://github.com/Minecrell/ServerListPlus/wiki/API#ban-api

Is there a reason you cannot use it? :)

**Comment by BrainStone** [comment]
Ok. I feel stupid now. Completely forgot about it.  
All I saw was that there's no API and that's when I created the issue.
