### ISSUE TITLE
Out of date client

### ISSUE THREAD

**Issue by Mysx-rage** [Minecrell/ServerListPlus#277]
Im using server list plus and on the minecraft server list its saying my client is out of date but still lets me join

**Comment by Mysx-rage** [comment]
https://gist.github.com/Mysx-rage/26cc8fc9e99f937996dea6a7ae4a8a12 this is config file

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems
