### ISSUE TITLE
/slp enable Does'nt work

### ISSUE THREAD

**Issue by Alfonso87639** [Minecrell/ServerListPlus#279]
Pls i need help, i tried to run SLP on my Sponge Server and the comman /slp or /slp enable does'nt work. 

I have the .config archive but the plugin does'nt work.

This is the lastest log
[latest.log](https://github.com/Minecrell/ServerListPlus/files/4310490/latest.log)

**Comment by Minecrell** [comment]
There is a syntax error in your configuration.

**Comment by Alfonso87639** [comment]
Thank you very mucho, it's fixed, but favicon does'nt load :(
