### ISSUE TITLE
Can't run the plugin

### ISSUE THREAD

**Issue by MxndzaLoL** [Minecrell/ServerListPlus#280]
14.04 17:34:07 [Server] WARN Unexpected exception while parsing console command "slp"
14.04 17:34:07 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'slp' in plugin ServerListPlus v3.4.8 - plugin is disabled.
14.04 17:34:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
14.04 17:34:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Minecrell** [comment]
The actual error is earlier in the log.
