### ISSUE TITLE
The motd has "crashed" 

### ISSUE THREAD

**Issue by rosiejane** [Minecrell/ServerListPlus#282]
@Minecrell 

This plugin has randomly stopped working 

The motd has "crashed" so to speak. I cannot change the motd. I have even removed serverlistplus.jar from the server and rebooted the bungee server a few times and the motd is still showing!!!

Has anyone had this before? I cant remove/change the motd.

The plugin is removed and the motd still shows the motd that "was" in the serverlistplus config.

The motd has crashed and it cannot be changed or removed.

I have removed serverlistplus.jar from the bugneecord server and the motd is still showing.!!!!!
 

 The folder keeps coming back yet the .jar file is not installed!
![image](https://user-images.githubusercontent.com/54243352/79641415-600d1d00-818f-11ea-95d3-dca15a4a64b9.png)

 This is inside the serverlistplus folder
![image](https://user-images.githubusercontent.com/54243352/79641425-67342b00-818f-11ea-8f65-2378ced76b56.png)

Ugh! Help.

**Comment by Minecrell** [comment]
You probably have it in your BungeeCord configuration?

**Comment by rosiejane** [comment]
No not at all.

I have the defauklt buingeecord motd

**Comment by rosiejane** [comment]
If i type "/slp" in-game i get this message

![image](https://user-images.githubusercontent.com/54243352/79642071-44a41100-8193-11ea-982b-75e1103bae4c.png)

This happens in any of the survival servers and also the lobby.

Yet the serverlistplus..jar has been removed from the bungeecord server.

**Comment by Minecrell** [comment]
> Yet the serverlistplus.jar has been removed from the bungeecord server.

Well, clearly it's still somewhere :-) It's either still somewhere in the `plugins` folder or you didn't restart the proxy properly.

> Any way we can add each other on discord?

Sorry, I barely ever check Discord for new messages so this wouldn't help you :')

**Comment by rosiejane** [comment]
Trust me on this. The jar file is nowhere to be seen. It has been removed. 

I have checked every folder. it is not on the bungee server, or on any of the spigot servers

**Comment by rosiejane** [comment]
Even if i re add the plugin to bungee and do /slp enable and,or /slp reload. The motd does not change.

**Comment by Minecrell** [comment]
I trust you but that's just not how computers work. :) They don't remember magic code just because it was installed at some point (unless it's malware and installed itself somewhere hidden, but SLP is not designed to be malware).

I would expect that if you start a new BungeeCord server (in a separate folder) that SLP isn't installed there (otherwise it would be running on each BungeeCord server).

I'm afraid I cannot really help you with this issue. Clearly it must be still around somewhere. I don't think it is in any way related to this plugin. Sorry :/

**Comment by rosiejane** [comment]
I created a new bungee cord server (new folder) but i am still having the same issues.

I i log in to every server and type /slp i get this message. 
![image](https://user-images.githubusercontent.com/54243352/79741967-09702200-82fa-11ea-8b02-0027360ab49a.png)

But when i type /slp in the console to every server i get "unknown command"

Something definitely is not right.

**Comment by Minecrell** [comment]
Maybe you are not joining the BungeeCord server you are configuring, but rather some other one that is still running. :D
