### ISSUE TITLE
Player Hover Message

### ISSUE THREAD

**Issue by ghost** [Minecrell/ServerListPlus#285]
Hello, so when I first installed the plugin and enabled it, the player hover message was working. But now for reasons beyond my knowledge it is no longer working and I have no clue why.

No errors appear in console either. I am running SpongeForge 1.12.2-2838-7.2.0

My Config File:
https://pastebin.com/fMCvdzk8

**Comment by Sephiths** [comment]
I'm having the same issue. And it's making me want to look for an alternative. Anyone know a solution? I've seen other servers showcase their servers with separate lines.

**Comment by Momshroom** [comment]
see #296 for the solution to this

**Comment by Sephiths** [comment]
> see #296 for the solution to this

Thanks! This worked!
