### ISSUE TITLE
Cant setBanprovider

### ISSUE THREAD

**Issue by paul0665** [Minecrell/ServerListPlus#288]
![Screenshot_20200508-165305_1](https://user-images.githubusercontent.com/47947919/81389768-eabcb880-914c-11ea-8dce-cb8ea817155a.jpg)

Can anyone give me an example about this?

**Comment by Minecrell** [comment]
You need to get an instance of the `ServerListPlusCore`, e.g.

```java
ServerListPlusCore core = ServerListPlusCore.getInstance();
core.setBanProvider(new MyBanProvider());
```

**Comment by paul0665** [comment]
Same, cant use getInstance and 
setBanProvider

![Screenshot_20200508-205100_1](https://user-images.githubusercontent.com/47947919/81407337-cd4c1680-916d-11ea-8f6a-3f15e5c511fe.jpg)

**Comment by Minecrell** [comment]
I think the ban API is not available in the latest release. You need to add the development builds to your classpath.

If you are using Maven/Gradle, you can get them from https://repo.codemc.org/repository/maven-snapshots/

**Comment by paul0665** [comment]
Can't get it by maven, so I try add the jar and it work now, thanks.

PS:maybe should edit the wiki page? It said it can be use on newer than v3.3

**Comment by Minecrell** [comment]
That comment applies to the replacement API. But you're right, it should be properly documented.

**Comment by paul0665** [comment]
okay i find the way to import it now

        <repository>
            <id>serverlistplus-repo</id>
            <url>https://repo.codemc.org/repository/maven-snapshots</url>
        </repository>

        <dependency>
            <groupId>net.minecrell</groupId>
            <artifactId>ServerListPlus</artifactId>
            <version>3.5.0-20190601.204403-16</version>
            <classifier>Universal</classifier>
            <type>jar</type>
        </dependency>
