### ISSUE TITLE
Center MOTD&Banned feature not working

### ISSUE THREAD

**Issue by vaio2005** [Minecrell/ServerListPlus#294]
Hello, I have a few questions. 
Is there an EASY way to center the MOTD?
I have added the Banned: (something) to the Config, but it doesn't work. Does the plugin have to be installed on the bungeecord or the individual spigot servers? (Using MaxBans on spigot servers)

**Comment by Minecrell** [comment]
> Is there an EASY way to center the MOTD?

You can add spaces to center it manually.

> I have added the Banned: (something) to the Config, but it doesn't work. Does the plugin have to be installed on the bungeecord or the individual spigot servers? (Using MaxBans on spigot servers)

SLP should be installed on the BungeeCord server. The "Banned" option will only work if you have a supported ban plugin installed on BungeeCord, which isn't the case for MaxBans as far as I know.
