### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by KAPLEGOMAN** [Minecrell/ServerListPlus#297]
Hello !
Is this plugin is available for the 1.15.2 minecraft version ?
Thanks,
KAPLEGOMAN

**Comment by Minecrell** [comment]
Nobody complained that it doesn't work there, yet...

**Comment by Andre601** [comment]
The plugin is working on 1.15.2 without any issues. Just make sure that you're using the right version of ProtocolLib, when using it on a Spigot/PaperMC version.

I myself use it on a 1.15.2 PaperMC server without any errors or similar (Just the server nagging randomly about SLP not shutting down properly when stoping the server)
