### ISSUE TITLE
Newlines in `%random_players%` no longer work in hover

### ISSUE THREAD

**Issue by cyberkitsune** [Minecrell/ServerListPlus#298]
I currently use `%random_players%` to display player names on hovering over the player count. As of 1.16 it now does this:
![Image of Bug](https://assets.cyberkitsune.net/share/javaw_2020-07-04_17-17-48.png)

**Comment by Minecrell** [comment]
See workaround in https://github.com/Minecrell/ServerListPlus/issues/296#issuecomment-650985707
