### ISSUE TITLE
player head favicon not working

### ISSUE THREAD

**Issue by titustitus98** [Minecrell/ServerListPlus#300]
Hi so I attempted adding the player's head as the server icon using these methods:

1. I tried using the configuration shown in the wiki but it did not work and I got this error:
 07.07 12:03:08 [Server] WARN [ServerListPlus] [Core] Unknown configuration property: Heads @ FaviconConf
2. I tried using the configuration shown by default in the config files but it did not work and I got this error:
 07.07 12:08:10 [Server] WARN [ServerListPlus] [Core] Unknown configuration property: SkinSource @ FaviconConf

Please fix this
Plugin version: 3.4.8

**Comment by Minecrell** [comment]
Looks like you added the options to the wrong configuration section, take a look at the example configuration: https://github.com/Minecrell/ServerListPlus/wiki/Examples

**Comment by titustitus98** [comment]
Yes I did try the one from the example but this time it didn't send an error it just didn't put on the icon
