### ISSUE TITLE
Errors with Ban Manager 

### ISSUE THREAD

**Issue by Momshroom** [Minecrell/ServerListPlus#302]
After updating from SLP 3.4.8 to ServerListPlus-3.5.0-SNAPSHOT-Bukkit.jar, migrating my config and setting the Sample to multiple to fix the hover issue in 1.16.1 and then refreshing my server list in my client I get this error on console:
https://paste.gg/p/Momshroom/0ddd984698024e23bc761c408be5096f
Paper 92 (1.16.1)
SLP 3.5.0 Snapshot 
Ban Manager 7.2.2 http://dev.bukkit.org/bukkit-plugins/ban-management/

If I leave out the Banned: section entirely, I still get this error when Samples: Multiple: is set to true and a player refreshes their client server list or hovers over the listing.  (If I don't set that to true, the hover text all shows on one line):
https://paste.gg/p/Momshroom/54684277390e4cc39b2846e43a527fd8

My config at the time of that last error is:
https://paste.gg/p/Momshroom/3036ae71083e4fa1adf07bb3a9fa3e86

Any help would be greatly appreciated! Ty.

**Comment by ZEROOblivious** [comment]
Well i can say its not your ban manager due to 2 other people are reporting the same error in two other issues. I think its just a 3.5.0 Error..
