### ISSUE TITLE
[1.16.1] Sample: Multiple: True Brings new console error spam

### ISSUE THREAD

**Issue by DiegoDaniel** [Minecrell/ServerListPlus#303]
After fixin the 1 line hover problem -> [Online counter hover shows as a single line.](https://github.com/Minecrell/ServerListPlus/issues/296) 

Console gets spammed with this every 10 - 15 seconds.

https://pastebin.pl/view/f905c9f4

**Comment by ZEROOblivious** [comment]
Having the same problem on my 1.16.3 Server. 

https://pastebin.com/cLeTC1Kh

Anyone got any ideas?

**Comment by ZEROOblivious** [comment]
@Minecrell
