### ISSUE TITLE
Error Message when running Maintenance + SLP

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Minecrell/ServerListPlus#309]
I'm getting this error message when running SLP + Maintenance on Velocity.

https://hastebin.com/faruyuwusi.rb
I've spoken to the Maintenance dev and he is unable to figure out why this is happening, anything you can do on your side?

**Comment by Minecrell** [comment]
I suspect this could happen if Maintenance is enabled before ServerListPlus. Perhaps it would help to use some `@Subscribe(order = ...)` for the `ProxyInitializeEvent`.
