### ISSUE TITLE
Problem with HOVER in 1.16.3 WaterFall.

### ISSUE THREAD

**Issue by StromeX123** [Minecrell/ServerListPlus#310]
Hi, i have a many problem with hover in 1.16.3.

See image:

![image](https://user-images.githubusercontent.com/36533301/95584280-1b7b8380-0a46-11eb-9ab7-fc7a48839f74.png)

**Comment by SwagPancakes** [comment]
I also have this problem.

**Comment by Minecrell** [comment]
Workaround in https://github.com/Minecrell/ServerListPlus/issues/296
