### ISSUE TITLE
Suggestion: Custom Protocol

### ISSUE THREAD

**Issue by SwagPancakes** [Minecrell/ServerListPlus#316]
Please add custom protocol option so that I can change the name of my server to something like "1.8 - 1.16.3" instead of "Spigot <ver>" or "Paper <ver>" etc.

**Comment by Minecrell** [comment]
This sounds like https://github.com/Minecrell/ServerListPlus/wiki/Status-Configuration#outdated-version

**Comment by SwagPancakes** [comment]
Oh nice
