### ISSUE TITLE
Plugin incompatible with 1.16.4 

### ISSUE THREAD

**Issue by OhNo2** [Minecrell/ServerListPlus#319]
I am using this plugin on my bungee server, and after updating to the most recent build for 1.16.4 the plugin stopped working, and my server defaulted back to it's old motd and the other features stopped working

**Comment by OhNo2** [comment]
Oh! forgot to mention,

The plugin was working fine on the server before the update

**Comment by Minecrell** [comment]
I tested it earlier today and it seemed to work just fine. Closing.
