### ISSUE TITLE
Plugin loads, but doesn't work

### ISSUE THREAD

**Issue by WolfyRed** [Minecrell/ServerListPlus#327]
The plugin loads in just fine, it has a `config.yml`, it has a plugin folder, it loads in and everything is okay.

The only problem is... **it doesn't do it's job!**

Not even on the exact version the server is set to, will the plugin do what it was downloaded and placed in the plugins folder to do.

The Server MOTD doesn't change *(line 1 nor line 2 of the MOTD)*, hovering over the player count in the Server list does the default thing *(which is to have no message)*, and etc. **No special features are occurring**, only the plugin loading is occurring!

![image](https://user-images.githubusercontent.com/66114400/109107163-3aca3300-76ff-11eb-92ad-611f9e50a8cd.png)

**Server version:** final Release for 1.12.2
**Plugin version:** ServerListPlus v3.4.8 (Spigot) `(ServerListPlus-3.4.8-Universal.jar)`

**Comment by Minecrell** [comment]
Well yeah it doesn't do anything by default. You need to enable it with a command.
