### ISSUE TITLE
Got this error to nag you here:

### ISSUE THREAD

**Issue by UppishBuzzard87** [Minecrell/ServerListPlus#328]
`Nag author: 'Minecrell <https://github.com/Minecrell>' of 'ServerListPlus' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.`

**Comment by Minecrell** [comment]
Which platform is this? Bukkit/Spigot/BungeeCord/...?

**Comment by UppishBuzzard87** [comment]
I'm on Paper Spigot 1.16.5

**Comment by UppishBuzzard87** [comment]
I mean, the plugin still works just fine, but I was wondering about that error

**Comment by Minecrell** [comment]
Hmm, I don't see what's wrong right now, I **am** shutting down those tasks. In any case, it should be save to ignore for now :D

**Comment by UppishBuzzard87** [comment]
okay, thank you ;)
