### ISSUE TITLE
Causing Hosting Suspensions

### ISSUE THREAD

**Issue by BeardedCamper** [Minecrell/ServerListPlus#329]
latest plugin is being flagged as having a backdoor malware by server hosts.

Have had two servers shutdown and suspended as ServerListPlus is flagging the antimalware systems as having a backdoor.

**Comment by Minecrell** [comment]
That's absolutely non-sense, at least if you downloaded the plugin from the official sources (e.g. here from GitHub Releases). Plus, there is no need to trust my prebuilts, if you have concerns please check the source code yourself and compile the plugin from source if necessary.

If these "antimalware systems" are out of your control, please contact your server host to get them fixed. Thanks!
