### ISSUE TITLE
Version Text Bug

### ISSUE THREAD

**Issue by arttwart** [Minecrell/ServerListPlus#332]
When I use Server List Plus 3.5.0 Build 443 with Protocol Lib 4.6.0, and if I use Version setting (the text when players do not have the required Minecraft version), it shows that version text even if I join with correct version. I can still join to the server, but it shows the version text.

Without Protocol Lib, it is working very well.

Here is my config: https://srcb.in/epZPE92s2J

I am using latest Paper 1.16.5 build.

**Comment by Minecrell** [comment]
Can reproduce this. Kind of weird.

**Comment by Minecrell** [comment]
Ah yeah actually it's pretty obvious why this happens. With ProtocolLib+Paper installed SLP will handle the server ping twice at the moment. So the `Slots` feature will change the protocol version, making SLP thing the client is outdated, and then the ProtocolLib handler will mess things up. Hmm.
