### ISSUE TITLE
Motd Problem

### ISSUE THREAD

**Issue by athkiasaris1** [Minecrell/ServerListPlus#333]
The problem I have is that sometimes the custom motd comes up and other times the default one comes up
![dsdddd](https://user-images.githubusercontent.com/53872050/114896638-2eb64400-9e19-11eb-973e-7450fc8d82df.PNG)

My config: https://hastepaste.com/raw/CfxKSY3i

**Comment by Minecrell** [comment]
Well, you set two possible "motds" in the `Description` list. SLP will choose one of them randomly. If you just want one of them, you should remove the other one.

**Comment by athkiasaris1** [comment]
I did not notice that. Thanks for letting me know
