### ISSUE TITLE
Incompatible Version?

### ISSUE THREAD

**Issue by ChitterChatter** [Minecrell/ServerListPlus#335]
Hi there, 

This is a screenie of our MOTD.

![image](https://user-images.githubusercontent.com/28234726/115171515-0710e700-a078-11eb-884d-aaea3af63850.png)

Our hover thingies work, but I am wondering how to change the config so that something is displayed where the Incompatible Version is - it would normally be the ping right? 

I am just not quite sure what to change or what to put in along with where to put it to make that go away and have the server version there or whatever. 

Here is my config:

https://pastebin.com/RpgJ5bpe

**Comment by athkiasaris1** [comment]
You can't change that, I think.

**Comment by Minecrell** [comment]
The outdated version is a side effect of using the custom player slots feature, please read https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems carefully.
