### ISSUE TITLE
RGB color format no showing on my 1.16 server.

### ISSUE THREAD

**Issue by arima0k** [Minecrell/ServerListPlus#346]
It just show white text on all players that connect.

![Screenshot_2021-05-14_19-33-08](https://user-images.githubusercontent.com/25037200/118342923-41d93400-b4eb-11eb-9325-0e3e63588e55.png)

**Comment by arima0k** [comment]
Other servers looks ok I don't know where I'm wrong
![image](https://user-images.githubusercontent.com/25037200/118343862-f9247980-b4f0-11eb-9734-a0f278f33b93.png)

**Comment by Minecrell** [comment]
Perhaps this https://github.com/Minecrell/ServerListPlus/issues/345#issuecomment-838275141?

**Comment by Minecrell** [comment]
@arima0k Did you solve the problem?

**Comment by arima0k** [comment]
> @arima0k Did you solve the problem?

Yes thank you.
