### ISSUE TITLE
3.5.0?

### ISSUE THREAD

**Issue by Wawwior** [Minecrell/ServerListPlus#348]
In the wiki you mentioned that v3.5.0 is required for rgb-hex colors to work, but it appears to me that 3.5.0 does not exist.
So what now?

**Comment by Minecrell** [comment]
You can download the development builds from: https://ci.codemc.org/job/Minecrell/job/ServerListPlus/

I still need to finish up two features for 3.5.0, then it's mainly a matter of some testing before I could make a new release. So, if you want RGB colors take the development builds and report if something isn't working correctly :)

**Comment by Assassin4b** [comment]
Ouh thank you, i tried it and it worked! Only problem is that rgb does not work on the hover message over the player count.
But still, great plugin!

**Comment by Minecrell** [comment]
> Ouh thank you, i tried it and it worked! Only problem is that rgb does not work on the hover message over the player count.
But still, great plugin!

I don't think the client allows that. The hover message is a list of players at the end, we just abuse it and put colored messages in place of the player names. The client still allows the typical color codes (`§c` etc) there atm, but not RGB.
