### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by PersonalDom** [Minecrell/ServerListPlus#359]
Hey there. My ping counter just says Incompatible version. Does anyone know why/how to fix it?

Plugin is installed on waterfall, and here is my config:

<details>
<summary>SLP Config</summary>

[ServerListPlus.yml.zip](https://github.com/Minecrell/ServerListPlus/files/6642895/ServerListPlus.yml.zip)

</details>

Here is a screenshot:
<img width="1382" alt="Screenshot 2021-06-12 at 22 12 49" src="https://user-images.githubusercontent.com/65628740/121789135-5fbdb580-cbcb-11eb-90e9-35176a6a9c0d.png">

**Comment by Minecrell** [comment]
Please read https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems. This is a side effect of using the "custom player slots" feature. If you remove `Slots:` from your configuration, it will disappear.

**Comment by PersonalDom** [comment]
Ah, thank you!
