### ISSUE TITLE
Multi-line error

### ISSUE THREAD

**Issue by Spiderjockey02** [Minecrell/ServerListPlus#361]
I have this code for mulit-line hover:
```
Players:
    Hover:
    - |-
      &aWelcome to &4Redstone &7Valley&a!

      - &aSurvival: &e%online@survival%/20 players online
      - &aCreative: &e%online@creative%/20 players online
      - &aSkyblock: &e%online@skyblock%/20 players online

      &aJoin now and play together with %random_player% ...
```
but it results in some strange symbols and all on one line (client 1.17 on bungeecord).
![image](https://user-images.githubusercontent.com/55885015/122643112-ddbb1880-d105-11eb-9b21-6ef8672f8bb9.png)

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/issues/296#issuecomment-650985707
