### ISSUE TITLE
y my server have: "incompatible version!"

### ISSUE THREAD

**Issue by 6test55566** [Minecrell/ServerListPlus#362]
![image](https://user-images.githubusercontent.com/77003234/123427536-6a197f80-d5cd-11eb-83b5-cf300b47af2b.png)
this is what i see on my server 
how to fix it plz?

**Comment by Minecrell** [comment]
Perhaps https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots#problems

**Comment by 6test55566** [comment]
ty @Minecrell 
![image](https://user-images.githubusercontent.com/77003234/123428545-984b8f00-d5ce-11eb-84d3-8b8bb30c7a27.png)
