### ISSUE TITLE
Issue with %gradient% placeholder in custom slots

### ISSUE THREAD

**Issue by NotCoolKiwi** [Minecrell/ServerListPlus#363]
Issue
=
The `%gradient%` placeholder shows seemingly random colors when in custom slots.

Config
=
Here is the part of the config in question:
```yaml
    Slots:
    - '&a%gradient#45bf55#00abd8#45bf55%|||||||||||||||||||||||||||||||| %online%/%max% ||||||||||||||||||||||||||||||||%gradient%'
```

Example/Result
=
This is what is displayed to the user/player:

![image](https://user-images.githubusercontent.com/60015960/123456021-fb75fb00-d5a7-11eb-882b-717b784b6179.png)

**Comment by Minecrell** [comment]
You cannot have RGB colors in custom color slots. TBH it's surprising it produces something useful at all :D

**Comment by NotCoolKiwi** [comment]
Okay. Thank you for your help!
