### ISSUE TITLE
How to get gradient text?

### ISSUE THREAD

**Issue by AeroSpace8** [Minecrell/ServerListPlus#365]
So I was looking through the GitHub, and saw that you could get a gradient text. When I tried this on my motd it did not work. I am running paper, on a 4gb server.

**Comment by Minecrell** [comment]
> **Note:** ServerListPlus 3.5.0 required (although it works sometimes with the alternative syntax on older versions). Until it's released you can [download the development builds](https://ci.codemc.io/job/Minecrell/job/ServerListPlus/). Please report if you find any issues. On Bukkit with ProtocolLib installed you need at least build 501 from https://ci.dmulloy2.net/job/ProtocolLib/.
