### ISSUE TITLE
The problem with the gradient

### ISSUE THREAD

**Issue by W1se-byte** [Minecrell/ServerListPlus#366]
Hello, there was such a problem. You can not insert two separate gradient codes in one line, otherwise you get a mess. Can you fix it?
![Безымвкамывянный](https://user-images.githubusercontent.com/85458923/124361931-a175d500-dc3a-11eb-9504-f00414f3c62d.png)
![Безымяннцукый](https://user-images.githubusercontent.com/85458923/124361932-a2a70200-dc3a-11eb-96b1-eba856f36639.png)
&r &r &r &r &r &r &r &r &r &r &r &r &r &r &r &r %gradient#52187F#A72FFF%●●●%gradient% &#A72FFF&lＦＵＴ&f&lＷＩＳＥ %gradient#FFFFFF#7F7F7F%●●●%gradient%

**Comment by Minecrell** [comment]
Please post the broken example as string, not image, so I can copy it for testing.

**Comment by W1se-byte** [comment]
&r &r &r &r &r &r &r &r &r &r &r &r &r &r &r &r %gradient#52187F#A72FFF%●●●%gradient% &#A72FFF&lＦＵＴ&f&lＷＩＳＥ %gradient#FFFFFF#7F7F7F%●●●%gradient%

**Comment by W1se-byte** [comment]
> Пожалуйста, опубликуйте сломанный пример в виде строки, а не изображения, чтобы я мог скопировать его для тестирования.

Ready, when can you fix the problem? It's just that this is the only convenient plugin.

**Comment by Minecrell** [comment]
I will investigate the problem sometime soon, please be patient. :)
