### ISSUE TITLE
Question about Version.Protocol

### ISSUE THREAD

**Issue by iGabyTM** [Minecrell/ServerListPlus#368]
Would be possible to make this a list of IDs or show the outdated version text only if the client's version is lower than what's specified, but not newer?
For instance the id for 1.17 is 755, on my server we have ViaVersion so people can connect with 1.17.1 (756) but if you ping the server, it will display the outdated version text, even though you can join the server.

**Comment by Minecrell** [comment]
If you have ViaVersion you shouldn't make use of `Version.Protocol`. ViaVersion should change the protocol version for you and then the outdated version text should be only be shown when relevant.
