### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by razincp** [Minecrell/ServerListPlus#370]
the slp commands are not working
![image](https://user-images.githubusercontent.com/88160336/130125442-49999357-460d-49a3-8743-9609161df655.png)
its not working sir

**Comment by Minecrell** [comment]
Looks like there is an error earlier in your log that prevented SLP from loading. Please post the whole log.

**Comment by razincp** [comment]
![image](https://user-images.githubusercontent.com/88160336/130182096-40779d0e-ae44-4fb0-8a5a-91ef3a8f0892.png)

which log you want sir

**Comment by Minecrell** [comment]
`latest.log`...
