### ISSUE TITLE
The /slp enable doesn't work

### ISSUE THREAD

**Issue by kenkena12** [Minecrell/ServerListPlus#371]
here's my latest
dunno what todo
[latest.log](https://github.com/Minecrell/ServerListPlus/files/7020344/latest.log)

**Comment by Minecrell** [comment]
It says pretty clearly what is wrong in your configuration:

```
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 39, column 1:
    	%gradient#FD0000#2BCBFD#3857FD# ... 
    ^

**Comment by kenkena12** [comment]
how do you fix it??
sorry for asking more

**Comment by Minecrell** [comment]
`Do not use \t(TAB) for indentation`
