### ISSUE TITLE
How to install correctly on Bungee

### ISSUE THREAD

**Issue by HysteriaMC** [Minecrell/ServerListPlus#376]
I've installed the plugin properly on Bungee, however, Placeholders do not work, is there a reason for this?

**Comment by Minecrell** [comment]
Which placeholders do not work? Please post your configuration and state exactly what "do not work" means. You do not see any changes in the server list? The placeholders are not replaced correctly?

**Comment by HysteriaMC** [comment]
I've tried the %server_countdown% placeholder from PlaceholderAPI, it returns blank space. I have installed PAPI.

By "Does not work" I mean that nothing appears, no placeholder actually shows.

**Comment by Minecrell** [comment]
I don't think PlaceholderAPI supports BungeeCord...
