### ISSUE TITLE
%player% returns to default option, even though player has already joined the network (more than) once.

### ISSUE THREAD

**Issue by GoedendagMC** [Minecrell/ServerListPlus#378]
The title says it all, how should I go about debugging this?

**Comment by Minecrell** [comment]
Perhaps the player IP is changing like every day. This is not uncommon. The feature depends on tracking the player IP address, if it changes there is no way to detect who the connecting player is.

**Comment by GoedendagMC** [comment]
Player IP is not changing. I think it might either be because of Flamecord or because of TCPSHIELD.

**Comment by Minecrell** [comment]
Uh, never heard of either of that. You can check the `PlayerCache.json` (or something like that) in the `ServerListPlus` folder, look for the player's IP and then check if that IP is connecting when the player pings the server.

**Comment by GoedendagMC** [comment]
PlayerCache.json is perfectly correct. I think it has to do with TCPShield not correctly forwarding the IPs in the pings. Thanks anyway!
