### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Peanutis1mo** [Minecrell/ServerListPlus#384]
Hello, how do i make the motd centered? i tried it like that but when the first line is more behind the second it sends errors, i just want the motd to be centered

Description:
  - |-
                    &8■ &8/&7/ &b&lDiamondlands &3&lNetwork &7\&8\ ■
                    &f&lNové Lobby! &b&ndiscord.gg/vqVYEAaTmp

**Comment by stephan-gh** [comment]
It's easiest to put a color code at the beginning of the line, e.g.

```yaml
Description:
  - |-
    &8                ■ &8/&7/ &b&lDiamondlands &3&lNetwork &7\&8\ ■
    &f                &lNové Lobby! &b&ndiscord.gg/vqVYEAaTmp
```

**Comment by Peanutis1mo** [comment]
thanks
