### ISSUE TITLE
Placeholders not working

### ISSUE THREAD

**Issue by Deeptanil** [Minecrell/ServerListPlus#386]
Hi, so as placeholders api (papi) can't be ran on a bungeecord server, i can't use the countdown placeholder. 
Is there a way to have slp on a hub, and then on the server list, that slp's config will be shown? 
Or some other way??

Please reply quickly! I've a reset coming out in 3 days!

**Comment by stephan-gh** [comment]
> Please reply quickly! I've a reset coming out in 3 days!

Sorry, I cannot provide priority support.

> Is there a way to have slp on a hub, and then on the server list, that slp's config will be shown?

I believe BungeeCord has some functionality to forward pings to backend servers. You would need to do some research about how to configure it properly though. (I don't know how, sorry.)

> Or some other way??

Well, the obvious way would be if someone adds a countdown placeholder to SLP. :)

**Comment by Deeptanil** [comment]
> Sorry, I cannot provide priority support.
You did tho 😂 thanks!

Okay. Thanks!

**Comment by Deeptanil** [comment]
I did the changes but... Somehow still didn't work... `{server_countdown_dd.MM.yyyy.H.m.Z_11.02.2022.07.30.+0530}`

**Comment by stephan-gh** [comment]
Make sure you use the SLP development builds, it doesn't work with the release version yet.

**Comment by Deeptanil** [comment]
Ohk
