### ISSUE TITLE
Can't have new line in Hover, favicon not working.

### ISSUE THREAD

**Issue by Harsh1625** [Minecrell/ServerListPlus#388]
when i try having a new line in hover it just puts an LF icon instead of a new line, i tried customizing favicon from the examples that were in the github itself but serverlistplus just says [ServerListPlus] [Core] Unknown configuration property: URLs @ FaviconConf even if it was customized with the help of the github itself idk if i am doing something wrong but if that's the case the examples are confusing and must have a better explaination.

**Comment by stephan-gh** [comment]
> when i try having a new line in hover it just puts an LF icon instead of a new line

https://github.com/Minecrell/ServerListPlus/issues/296#issuecomment-650985707 (or update to the dev builds, it's fixed there)

> i tried customizing favicon from the examples that were in the github itself but serverlistplus just says [ServerListPlus] [Core] Unknown configuration property: URLs @ FaviconConf even if it was customized with the help of the github itself

You probably added it to the wrong configuration section, everything you do needs to be added to the `!Status` part of the configuration. See https://github.com/Minecrell/ServerListPlus/wiki/Examples for a full example.

> idk if i am doing something wrong but if that's the case the examples are confusing and must have a better explaination.

Specific suggestions how to improve the wiki would be much appreciated. It is a common mistake to add the Favicon part to the wrong section of the configuration but I am not entirely sure how to make that more clear.

**Comment by Harsh1625** [comment]
> > when i try having a new line in hover it just puts an LF icon instead of a new line
> 
> [#296 (comment)](https://github.com/Minecrell/ServerListPlus/issues/296#issuecomment-650985707) (or update to the dev builds, it's fixed there)
> 
> > i tried customizing favicon from the examples that were in the github itself but serverlistplus just says [ServerListPlus] [Core] Unknown configuration property: URLs @ FaviconConf even if it was customized with the help of the github itself
> 
> You probably added it to the wrong configuration section, everything you do needs to be added to the `!Status` part of the configuration. See https://github.com/Minecrell/ServerListPlus/wiki/Examples for a full example.
> 
> > idk if i am doing something wrong but if that's the case the examples are confusing and must have a better explaination.
> 
> Specific suggestions how to improve the wiki would be much appreciated. It is a common mistake to add the Favicon part to the wrong section of the configuration but I am not entirely sure how to make that more clear.

ohhh my bad

**Comment by zhgt** [comment]
Hello! The same thing is happening to me. How did you solve it?
