### ISSUE TITLE
I have my configuration file correct and i cant figure out why the hover message dont appear on bungeecord 

### ISSUE THREAD

**Issue by kingelectrixgyt** [Minecrell/ServerListPlus#390]
[ServerListPlus.zip](https://github.com/Minecrell/ServerListPlus/files/8319159/ServerListPlus.zip)
^ my config is above in the zip file and all the bungee plugins i have are: AdvancedBan, BuyCraftx, FallBackServer,LiteAnnouncer, LuckPerms-Bungee, PremiumVanish, ServerListPlus-3.4.8, Skin Restorer, Slash Server

**Comment by kingelectrixgyt** [comment]
![Capture4](https://user-images.githubusercontent.com/38532714/159361867-0a808d8b-4ba2-4cc8-9291-332111fca6cf.PNG)
![Capture1](https://user-images.githubusercontent.com/38532714/159361871-d4a27149-6346-46de-b59f-294e7605ed94.PNG)
It Should look something similiar to the MCLegends one but It Doesnt Show up i have restarted the proxy and did /slp enable

**Comment by stephan-gh** [comment]
The config seems fine but you should update to the 3.5.0 development builds or change the configuration as follows:

```yaml
Samples:
  Multiple: true
  DynamicPlayers: false
```
