### ISSUE TITLE
Possible update to 1.19?

### ISSUE THREAD

**Issue by YTPSDanDie** [Minecrell/ServerListPlus#396]
Hi,
Wondering if there is a possibility of getting this plugin updated to 1.19, please?
Kind Regards, Daniel.

**Comment by stephan-gh** [comment]
Is there an error?

**Comment by ResoluteWears** [comment]
> Is there an error?

I don't understand your question. We are wanting it updated to support 1.19. Preferably 1.18 as well. Kind of hard to get an error when it doesn't enable on the server anyway.

**Comment by YTPSDanDie** [comment]
Yeah, so the issue is it doesn’t load on any server so I’m guessing by your reply you are hoping to upload a new version for 1.18 and 1.19 but working on them currently. Appreciate your time.

**Comment by stephan-gh** [comment]
The plugin should either just work on 1.19 or there should be an error in the console that describes why it is not working.

**Comment by YTPSDanDie** [comment]
I will screenshot console once home.

**Comment by Canecorso00** [comment]
![obraz](https://user-images.githubusercontent.com/48067359/187035631-194dad60-bebd-41c6-af2f-78c33865fa6d.png)

**Comment by stephan-gh** [comment]
Seems unrelated, try deleting `plugins/ServerListPlus/PlayerStorage.json` (or something like that). Make a backup first if you want (or just rename the file).

**Comment by YTPSDanDie** [comment]
Closing as there isn't a problem with plugin anymore!
