### ISSUE TITLE
Keeps saying internal error occured when i change the yml file

### ISSUE THREAD

**Issue by BryanThePotato** [Minecrell/ServerListPlus#397]
I'm just trying to change the motd to   
  
  
  - |-
  &eWelcome to &9Vanilla &bSurvival&r
  &e(&61.19.3 - 1.19.2&e)&r
  - |-
  &eWelcome to &9Vanilla &bSurvival&r &6&l%player%&r
  &e(&61.19.3 - 1.19.2&e)&r
  
  
  in 1.19.2

**Comment by stephan-gh** [comment]
Please double-check your configuration file syntax. Otherwise please post the full configuration and the error from the console log.
