### ISSUE TITLE
Not reading ServerListPlus.yml content

### ISSUE THREAD

**Issue by charlie-moomoo** [Minecrell/ServerListPlus#398]
I have a BungeeCord server with ServerListPlus on it. ServerListPlus works perfectly when I run the server on my Windows computer, but when I run it on my new Ubuntu VPS, it is not reading the content of ServerListPlus.yml, it just shows up the default MOTD of ServerListPlus.

**Comment by stephan-gh** [comment]
Did you `/slp enable`?

**Comment by charlie-moomoo** [comment]
> Did you `/slp enable`?

Yes, I did! But it just shows something like [this](https://cloud.githubusercontent.com/assets/3035868/3996671/d00522a8-2937-11e4-9ced-6858df683990.png).

**Comment by stephan-gh** [comment]
That looks like the default config, suggesting that you did not make any changes to the `ServerListPlus.yml` on the server.

**Comment by charlie-moomoo** [comment]
I edited the file! But it still shows the MOTD in the default config.

Stephan ***@***.***> 於 2023年1月25日 週三 20:22 寫道：

**Comment by charlie-moomoo** [comment]
I just found out, in Windows, it will use the `serverlistplus` folder, but in Linux, it will use `ServerListPlus` instead. After I edited the config in the `ServerListPlus` folder, everything worked.
