### ISSUE TITLE
Playercount hover Glitched for Newer Versions

### ISSUE THREAD

**Issue by RobertGaminPlayz** [Minecrell/ServerListPlus#399]
I don't exactly know what versions it shows but so far all I know is it looks glitched in 1.19+
![image](https://user-images.githubusercontent.com/123712859/215006274-a4980dae-8ecf-4204-8973-c2baaa83a895.png)
On 1.8.9 it looks like this (The way it should look)
![image](https://user-images.githubusercontent.com/123712859/215006339-fe3951c9-fcca-4cb4-99db-7af556f92673.png)

**Comment by RobertGaminPlayz** [comment]
Other servers who also has the hover on the playercount looks normal for 1.19 versions. I know it doesn't support 1.19 but it supports 1.17 with the gradient color. So, it should at least still be compatible with 1.19 (I think) and if you can just make it compatible with 1.19+

**Comment by stephan-gh** [comment]
https://github.com/Minecrell/ServerListPlus/issues/296
