### ISSUE TITLE
Get favicons from the Web asynchronously for newer BungeeCord builds.

### ISSUE THREAD

**Issue by Minecrell** [Minecrell/ServerListPlus#40]

**Comment by EazyFTW** [comment]
Mine is not working

**Comment by EazyFTW** [comment]
I get this error: 25.08 10:43:28 [Server] WARNING [Core] Unable to load favicon from URL: https://mc-heads.net/head/0558982295db4a8cbec56aab3550caa5/64 -> javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by Minecrell** [comment]
@EazyFTW Does that happen every time or did it just happen once?

**Comment by EazyFTW** [comment]
Every time

**Comment by EazyFTW** [comment]
I tried https://visage.surgeplay.com/ and https://mc-heads.net/

**Comment by EazyFTW** [comment]
I have a suggestion to, if you put %center% before a line in in the motd it will center the motd, that would be amazing!

**Comment by EazyFTW** [comment]
@Minecrell ??

**Comment by Minecrell** [comment]
@EazyFTW Please open a new issue with a copy of your configuration. For the `%center%` request, there is already https://github.com/Minecrell/ServerListPlus/issues/106. I will check soon if this can be implemented easily.

**Comment by EazyFTW** [comment]
ok

**Comment by EazyFTW** [comment]
@Minecrell about the

**Comment by Minecrell** [comment]
Yes, please create a new issue here: https://github.com/Minecrell/ServerListPlus/issues/new

**Comment by EazyFTW** [comment]
@Minecrell ok

**Comment by EazyFTW** [comment]
@Minecrell Created Here: #130
