### ISSUE TITLE
Bungeecord

### ISSUE THREAD

**Issue by PandaKeny** [Minecrell/ServerListPlus#401]
![image](https://github.com/Minecrell/ServerListPlus/assets/87780831/26940243-c04e-4116-bbe0-9f08ed091ffd)

**Comment by stephan-gh** [comment]
Try latest dev build from https://ci.codemc.org/job/Minecrell/job/ServerListPlus/

**Comment by PandaKeny** [comment]
> Try latest dev build from https://ci.codemc.org/job/Minecrell/job/ServerListPlus/

thanks it worked
