### ISSUE TITLE
Bungee - error on startup- Snakeyaml?

### ISSUE THREAD

**Issue by Swede37** [Minecrell/ServerListPlus#409]
Hi,
updating the network to 1.20.4, and getting an error on startup.  https://pastebin.com/mEERhdQL

Thanks in advance to anyone with some insight. I'm a bit rusty at the whole process so it is possible I just missed something.

**Comment by stephan-gh** [comment]
Try uppdating SLP to the latest version (3.5.0).

**Comment by Swede37** [comment]
Unfortunately , that error was while using 3.5.0.  Tried the version from Spigot, and it didn't work so I tried the release from Github and it is giving that error.

**Comment by Swede37** [comment]
Found the fix, in case anyone else runs into it. I needed to use [version 3.5.1](https://ci.codemc.io/job/Minecrell/job/ServerListPlus/)

**Comment by stephan-gh** [comment]
Something else must be wrong with the 3.5.0 you downloaded then because 3.5.1 should be 100% identical to the latest release at the moment... :confused:
