### ISSUE TITLE
Add support for more server implementations.

### ISSUE THREAD

**Issue by Minecrell** [Minecrell/ServerListPlus#41]
There are a lot of new server implementations now, and ServerListPlus should support at least the most used of them:

- [x] Standalone version (lightweight server just providing the server status ping)
- [x] [CanaryMod](http://canarymod.net)
- [x] [Sponge](http://spongepowered.org)

**Comment by lexware** [comment]
Is Sponge ready to start development for a version of ServerListPlus?

**Comment by Minecrell** [comment]
Standalone version added, closing this.
