### ISSUE TITLE
Could not pass event StandardPaperServerListPingEventImpl to ServerListPlus v3.5.0

### ISSUE THREAD

**Issue by tomasalias** [Minecrell/ServerListPlus#421]
![image](https://github.com/user-attachments/assets/83438c4c-ada1-4873-8cd4-c0b84c3a391f)

**Comment by Tsoccerguy3** [comment]
updated plugin posted here https://github.com/FactionFrenzy/ServerListPlus/releases/tag/3.5.2-FACTION-FRENZY-CUSTOM-SNAPSHOT

**Comment by lungfesh** [comment]
crazy how this still isnt fixed
