### ISSUE TITLE
How, if possible, do I use specific MoTDs per domain?

### ISSUE THREAD

**Issue by CoolManTheCool** [Minecrell/ServerListPlus#422]
## Feature Request: Domain-Specific MoTDs in Velocity Network

**Description:**
I would like to request a feature for the Velocity proxy that allows for different Message of the Day (MoTD) configurations based on the domain used to ping the server. Currently, I have a Velocity network set up with forced hosts, which allows the servers to act independently. However, for better management and user experience, I want to display different MoTDs depending on the domain name used.

**Use Case:**
I run a network with multiple friends and we have different servers that should display unique MoTDs. For instance:
- When the server is pinged using "play.exampleone.com", it should show one MoTD.
- When the server is pinged using "play.exampletwo.com", it should display a different MoTD.

This feature would enhance the user experience by providing relevant server information based on the specific domain they use.

**Proposed Solution:**
Implement a domain-specific MoTD feature that checks the domain name used to ping the server and displays the corresponding MoTD. This could be configured in the `velocity.toml` or another relevant configuration file.

**Example Configuration:**
```
forced-hosts:
  "play.exampleone.com":
    motd: |
      &aWelcome to ExampleOne!
      &bEnjoy your stay! on ExmapleONE SMP
  "play.exampletwo.com":
    motd: |
      &aWelcome to ExampleTwo!
      &bHave fun and explore! on ExampleTWO smp
```

**Additional Context:**
- Velocity version: Velocity 3.3.0-SNAPSHOT (git-5154f029-b404)
- ServerListPlus v3.5.0 (Velocity)

This feature would greatly simplify management and improve the flexibility of running a multi-domain network with Velocity.

Thank you for considering this feature request!

**Contact:**
CoolManTheCool
noahgrimes0915@gmail.com
discord: CoolManTheCool (I perfer if you can contact me here as I do not check github often.)

edit: Made some stuff not red for some reason...?

**Comment by stephan-gh** [comment]
Sorry for the late reply. This is actually supported already I think? https://github.com/Minecrell/ServerListPlus/wiki/Virtual-Hosts
