### ISSUE TITLE
Plugin not loading on Sponge API 7

### ISSUE THREAD

**Issue by Ve6om** [Minecrell/ServerListPlus#428]
[Stack trace Here](https://paste.gg/p/anonymous/f2bfff0af8424e3daccce874e0905892
)

Same result with the latest dev build as well.

**Comment by stephan-gh** [comment]
`ServerListPlus-3.5.0-Server.jar` is the standalone version of SLP, download ` ServerListPlus-3.5.0-Universal.jar`

**Comment by Ve6om** [comment]
The issue is also occurring with `ServerListPlus-3.5.0-Universal.jar`: https://mclo.gs/CMU7EXR

This file is not corrupted, it's been downloaded straight from Sponge Ore multiple times, as-well as reuploaded multiple times. It's worth noting, the `3.4.7` release works without issue.

**Comment by stephan-gh** [comment]
SLP 3.5.0 doesn't support SpongeAPI 7 anymore since there was no good way to keep backwards compatibility due to major changes in SpongeAPI. It needs SpongeAPI 8+. So just keep using 3.4.7 for SpongeAPI 7. :)
