### ISSUE TITLE
Persistent favicon cache

### ISSUE THREAD

**Issue by frdmn** [Minecrell/ServerListPlus#51]
Hey @Minecrell 

First of all: awesome plugin, works like a charm and its very well documented. Superb!

I have one suggestion, though. At the moment, if you use the favicon feature, you won't see personalized favicons if you restart your server.

Would be nice if you could cache and store them locally for, let's say 24h before you need to refresh via a HTTP request.

Thanks in advance!

Edit: I'm using the Spigot build.

**Comment by Minecrell** [comment]
If you only want the _personalized_ favicons to work after a restart you can test the latest development builds, the name will be saved in a local JSON file in these. However, the favicon still needs to be downloaded again when the server is restarted. While I think this is a nice feature in general, implementing it is not that easy. You need to make sure the cache won't grow forever without being cleaned up after some time.

**Comment by frdmn** [comment]
@Minecrell I don't really care that the plugin needs to redownload them after a reboot, I just want to keep the accociations of players :)

Let me try the dev build...

**Comment by Minecrell** [comment]
@frdmn Better don't use it in production yet, I've noticed a few bugs I still need to fix when I was porting the plugin to Sponge.

**Comment by frdmn** [comment]
@Minecrell I just tried the dev build temporarily, works like a charm. Keeps the personal player<->favicon accociations across reboots.

If you think it'll break stuff, i'll downgrade to the latest recommended build until there is a new RB version of 3.4. :)

Thanks for your quick reply!

**Comment by Minecrell** [comment]
I'll keep this open as an idea for the future, downloading them again on every start might not be that efficient if the server is frequently restarted.

**Comment by frdmn** [comment]
Alright!
