### ISSUE TITLE
Plugin not work on Spigot 1.8.3 (v3.3.3)

### ISSUE THREAD

**Issue by TheAcastus** [Minecrell/ServerListPlus#55]
Hi, I have troubles with ServerListPlus = Not work. Plugin isn't loaded, in log I see the following error:
http://pastebin.com/rtdiTYiz

I have latest version of ProtocolLib, Spigot 1.8.3 R0.1. I don't know, why plugin not works, I read it many times...

Please, Help!

Sincerely,
TheAcastus

**Comment by Minecrell** [comment]
You're not running Spigot 1.8.3 (that's Spigot 1.8). Make sure your running your new built JAR and not.an older one (e.g. if you need to upload it first). If you want to use ServerListPlus on 1.8 instead download the previous version instead (though you will also need a different ProtocolLib version.

**Comment by Minecrell** [comment]
(If you still can't get it working feel free to comment here again so we can see if something else is maybe wrong)

**Comment by DanielBakas** [comment]
Hey guys! I have the same problem, a lot of my most important plugins are not working since there's something wrong with ProtocolLib. This is what i got:
- Java JDK 8 40
- Spigot 1.8.3
- Latest ProtocolLib version
- All Essentials plugins updated to latest versions

This is my log: http://pastebin.com/V8QuSauE

**Comment by Minecrell** [comment]
@DanielBakas You don't even have ServerListPlus installed, are you sure it's a problem with it?

**Comment by DanielBakas** [comment]
Oh, i dont have it installed but im getting a ProtocolLib error. Do you know what could be causing it?

**Comment by Minecrell** [comment]
@DanielBakas It seems like a lot of plugins are not loading properly, the JAR files seem to be corrupted. Redownloading all of them could possibly help.

**Comment by DanielBakas** [comment]
I'll try that. Thanks. BTW, do you know any devs? Im looking for one to help us out on the server

**Comment by Minecrell** [comment]
@DanielBakas You can hire developers on SpigotMC in the Service and Recruitment forum: http://www.spigotmc.org/forums/hiring-developers.55/ (see http://www.spigotmc.org/threads/section-overview.31012/)

**Comment by DanielBakas** [comment]
Thanks
