### ISSUE TITLE
Erro onPacketSending while sending MOTD to the client

### ISSUE THREAD

**Issue by TheAcastus** [Minecrell/ServerListPlus#56]
Hi, today I downgraded to 3.3.2 (for Spigot 1.8) and while I click Multiplayer and server's motd started to load. In server console (log) I saw this error. It has two negative effects to the motd, when my cursor is hovering over the player count, nothing have been showed and player count online/max isn't edited.
And the console error... long error... Spamy spamy spam :D

http://pastebin.com/VncHVzpf

Sincerely,
TheAcastus

**Comment by Minecrell** [comment]
This looks a bit like you're using the wrong ProtocolLib version for your Spigot version. Try to use http://ci.shadowvolt.com/job/ProtocolLib/83/ instead.

**Comment by Minecrell** [comment]
I guess I can close this, if this wasn't fixed just write here again.

**Comment by TheAcastus** [comment]
Yeah, older version of ProtocolLib fix that. :)
