### ISSUE TITLE
Add UUID Favicon support

### ISSUE THREAD

**Issue by JustBru00** [Minecrell/ServerListPlus#59]
Could you add UUID favicon support? Or is there all ready such a thing and I just don't know how to do it?

Here is my config: http://pastebin.com/DuUJpz0a 

Thanks for your time.

**Comment by Minecrell** [comment]
I remember implementing something like `%uuid%` in the latest development builds but not exactly sure if it outputs the UUID with dashes or without dashes you would need to test this

**Comment by JustBru00** [comment]
Would you mind pointing me to the development builds :D

**Comment by Minecrell** [comment]
As [documented in the Wiki](https://github.com/Minecrell/ServerListPlus/wiki#download) and the README, Development Builds are available for download on my Jenkins server: http://ci.minecrell.net/job/ServerListPlus/
Please keep in mind they may be still a bit unstable or contain bugs - use them at your own risk.

**Comment by Minecrell** [comment]
There is `%uuid%` and `%_uuid_%` now:  
`%uuid%` prints something like `e63cec43-38f5-41d0-b7f3-8593ae0c862f`  
`%_uuid_%` prints something like `e63cec4338f541d0b7f38593ae0c862f`
