### ISSUE TITLE
Update for SpongeAPI changes

### ISSUE THREAD

**Issue by rnateh** [Minecrell/ServerListPlus#60]
I get this error when I use the "Sponge" one, any idea on how I can fix this and or what my stupidity is missing. (I've had no sleep so my problem solving isn't the best right now. http://prntscr.com/7l6efm

Maybe a outdated Sponge compared to the version your using?
http://prntscr.com/7l6hsg

**Comment by rnateh** [comment]
[Server thread/INFO]: Error occurred while executing command: org.spongepowered.api.text.Texts.fromLegacy(Ljava/lang/String;)Lorg/spongepowered/api/text/Text$Literal;

**Comment by Minecrell** [comment]
Ah, just need to update it for SpongeAPI changes

**Comment by rnateh** [comment]
Any clue which version I should update to or do you mean you need to udpate the sponge SLP to work with the new changes. Sorry about this, very tired xD

**Comment by Minecrell** [comment]
You need to wait until I fix it, will do in about an hour maybe

**Comment by rnateh** [comment]
Alright thank you. Sorry about my misunderstanding.

**Comment by Minecrell** [comment]
Should be fixed in latest dev build

**Comment by rnateh** [comment]
Hmm its now saying /slp enable or /slp in general isn't a command.

**Comment by rnateh** [comment]
http://ci.minecrell.net/job/ServerListPlus/280/
ServerListPlusSponge-3.4-SNAPSHOT.jar correct?

**Comment by rnateh** [comment]
Does this help at all? http://pastebin.com/X6ThVzfm

**Comment by TBotV63** [comment]
You might want to create another issue for that.

**Comment by Minecrell** [comment]
http://ci.minecrell.net/job/ServerListPlus/lastSuccessfulBuild/artifact/Sponge/build/libs/ServerListPlusSponge-3.4-SNAPSHOT.jar

**Comment by Minecrell** [comment]
You need to use the **latest** Sponge build as well (1.8-1446-2.1DEV-**498**)

**Comment by rnateh** [comment]
Alright I will test the latest version and get back to you in a few minutes.

**Comment by rnateh** [comment]
forge-1.8-11.14.3.1446.jar 

and

sponge-1.8-1446-2.1DEV-498 Correct? Sorry if I am a little confused. I tried to do that and it seems that it isn't registering "plugins/mods" again. I haven't gotten on top of this yet.
