### ISSUE TITLE
Error in console when trying to use the hover feature

### ISSUE THREAD

**Issue by Bennyboy1695** [Minecrell/ServerListPlus#65]
I recive this error when using either your example message or my own configured one. Everything works except for the hover feature
http://pastebin.com/cZXXGRXQ

**Comment by Minecrell** [comment]
You need to use the latest ProtocolLib release, older versions are not supported.

**Comment by Bennyboy1695** [comment]
That was using the very latest version of protocol lib, I had also tried rolling back both plugins and still got the same message

**Comment by Minecrell** [comment]
Have you tried the latest [ProtocolLib development build](http://ci.shadowvolt.com/job/ProtocolLib/)?

**Comment by Minecrell** [comment]
Closing this for now, please comment again if this is still an issue.
