### ISSUE TITLE
Doesn't Work.

### ISSUE THREAD

**Issue by Cexy** [Minecrell/ServerListPlus#69]
I tried using it with Bukkit and it just doesn't work. It is installed on my server but when i put my mouse on the Player count it doesn't work. Help?
![screenshot_1](https://cloud.githubusercontent.com/assets/15198754/10582834/c618b340-7657-11e5-9397-ddf321ffcb03.png)

**Comment by Minecrell** [comment]
Do you have ProtocolLib installed?

**Comment by Cexy** [comment]
No, I did not know i needed that. Sorry!

**Comment by Cexy** [comment]
i installeed it and it still does not work. Help?

**Comment by Minecrell** [comment]
Have you actually executed `/slp enable`?

**Comment by Cexy** [comment]
No! THANK YOU SO MUCH!!! THAT WORKEED!!! <3 <3 <3

**Comment by Cexy** [comment]
But question: with the "%online@world% how do i set the worlds? like the Hub world is labeled "world" so would i put %online@world% or %online@worldworld%

**Comment by Minecrell** [comment]
Please read the README or wiki next time before installing a plugin. Anyway, great that it is fixed now.

**Comment by Minecrell** [comment]
You use `@online@ENTERYOURWORLDNAMEHERE%` for the placeholder.

**Comment by Cexy** [comment]
ok ty
