### ISSUE TITLE
Need help, recomended plugin for spigot 1.8.2 version?

### ISSUE THREAD

**Issue by NickFirenzo** [Minecrell/ServerListPlus#70]
Hi,
I need help about 1.8.2 spigot version. On 1.8.3 or higer work great without errors an etc.
But on 1.8.2 version getting an errors.
And witch ProtocolLib is recomended for spigot 1.8.2 and ServerLisPlus?
Thanks

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/releases/tag/3.4

> **Note:** If you're using ServerListPlus on Spigot and you're not using 1.8.3 or newer you need to use special versions of ServerListPlus:

> - Spigot 1.8: [ServerListPlus v3.4-1.8](http://ci.minecrell.net/job/ServerListPlus/288/artifact/Bukkit/build/libs/ServerListPlusBukkit-3.4-1.8.jar)
- Bukkit/Spigot 1.7.x or Spigot 1.8 protocol hack: [ServerListPlus v3.4-1.7.X](http://ci.minecrell.net/job/ServerListPlus/288/artifact/Bukkit/build/libs/ServerListPlusBukkit-3.4-1.7.X.jar)

You need to download the version for Spigot 1.8. Install the latest ProtocolLib from https://www.spigotmc.org/resources/protocollib.1997/
