### ISSUE TITLE
Unable to start on Spigot 1.8.7 using SLP 3.4...

### ISSUE THREAD

**Issue by Collserra** [Minecrell/ServerListPlus#72]
I get the error
"Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.libs.com.google.gson.GsonBuilder"

I AM running Java 7, and I am using the latest (as of October 22nd) dev build of ProtocolLib.

The plugin does not give me any input using any of the commands, and there is no plugin folder.

**Comment by sgdc3** [comment]
What is slp?

**Comment by Collserra** [comment]
ServerListPlus, the acronym used for commands used by the plugin

**Comment by Minecrell** [comment]
It seems like you downloaded the wrong version for your server. This error will happen if you try to use the ServerListPlus build for 1.8 on a 1.8.3+ server. Please try to download the version from https://www.spigotmc.org/resources/serverlistplus.241/download?version=31463

**Comment by Minecrell** [comment]
Closing this for now, please comment here again if this is still an issue.
