### ISSUE TITLE
Hovering Playercount Issue.

### ISSUE THREAD

**Issue by YoloxPanda** [Minecrell/ServerListPlus#73]
Hey!

Awesome job on this plugin by the way! I ran into one small error with this plugin.

Here's the stack-trace - https://pnada.co/pastes/serverlistplusissue.txt

I can also provide the config.yml if needed :)

**Comment by Minecrell** [comment]
See https://github.com/Minecrell/ServerListPlus/issues/72#issuecomment-150538547

**Comment by YoloxPanda** [comment]
Issue still occurs.

[06:09:19 INFO]: ServerListPlus version 3.4
[06:09:19 INFO]: An extremely customizable server status ping plugin for Minecraft
[06:09:19 INFO]: Website: http://git.io/slp
[06:09:19 INFO]: Author: Minecrell <https://github.com/Minecrell>

**Comment by Minecrell** [comment]
That's not possible. Make sure you've really installed the version from https://www.spigotmc.org/resources/serverlistplus.241/download?version=31463

**Comment by YoloxPanda** [comment]
Are you sure, you are linking the correct version? I am still getting the same issue ;(

**Comment by YoloxPanda** [comment]
yeah same issue lol.

**Comment by Minecrell** [comment]
This seems to be actually caused by your ProtocolLib version, do you have the latest installed?

**Comment by YoloxPanda** [comment]
Thanks! Resolved the issue :)
