### ISSUE TITLE
ServerListPlus doesn't work on 1.8.8

### ISSUE THREAD

**Issue by NickFirenzo** [Minecrell/ServerListPlus#74]
My server is still on 1.8.8 version. I downloaded and installed slp plugin, but when type the command /slp, /slp reload, the chat goes out nothing. On /plugins display normal how and others with 'green' colors. Wich version of server list plus I need to work fine?
Installed ProtocolLib to latest version.

**Comment by Minecrell** [comment]
Can you post your full server log?

**Comment by Minecrell** [comment]
Can you post your full server log?

**Comment by NickFirenzo** [comment]
http://pastebin.com/ktP7t0C1

**Comment by Minecrell** [comment]
Are you using the latest Spigot version? Also, where did you download your ServerListPlus build from?

**Comment by NickFirenzo** [comment]
Yes

**Comment by Minecrell** [comment]
Where did you download your ServerListPlus build from?

**Comment by NickFirenzo** [comment]
Solved, thanks.
