### ISSUE TITLE
Bungeecord Question

### ISSUE THREAD

**Issue by Dooleylabs** [Minecrell/ServerListPlus#75]
I'm setting up a new bungeecord for the first time, and everything has worked so far, except for ServerListPlus. I haven't found any documentation about how to set it up on a bungee, so I figure it must be simple, yet not simple enough for me. I'm tried the latest recommended build and the latest dev build, but had no luck. Is there a special build or am I doing it wrong?

I'm using build 1091 of bungeecord and either build 306 or 307 of SLP. (Probably 306)

**Comment by Minecrell** [comment]
Please use the latest recommended build. You just need to drop the JAR into your BungeeCord plugins folder and follow the instructions in the Wiki/the plugin description.
