### ISSUE TITLE
Need help about PLAYER COUNT :)

### ISSUE THREAD

**Issue by NickFirenzo** [Minecrell/ServerListPlus#76]
Hi,
I need help about player count. How can I configure to show only online players on the server, In config.yml has no line where can I put %online% or etc :(

My config: http://pastebin.com/HMGnkfUf
I'd like this: http://prntscr.com/9jxfqi

Thanks :)

**Comment by Minecrell** [comment]
You need to add a custom player slot format to your configuration: https://github.com/Minecrell/ServerListPlus/wiki/Player-Slots

**Comment by NickFirenzo** [comment]
Where can I put this?
In witch place in config.yml?

Players:
    Slots:
    - '&7» &6&l%online%&c&l/&6&l%max%'

**Comment by Minecrell** [comment]
You need to add this to the default section. There is already the player hover stuff in your configuration, so you just need to place it below that. Here is an example: https://gist.github.com/Minecrell/b36a335b1d470c5f22d5#file-serverlistplus-yml-L58-L59

**Comment by NickFirenzo** [comment]
Solved, thanks :D
