### ISSUE TITLE
new placeholder for bungee 

### ISSUE THREAD

**Issue by Twi5TeD** [Minecrell/ServerListPlus#77]
oh ive only just seen that placeholder is there a placeholder to see  the highest amount of players placed like say my highest player count was 60 is would say 60

**Comment by Minecrell** [comment]
I'm pretty sure this exact placeholder exists already.

**Comment by Twi5TeD** [comment]
edited :)

**Comment by Minecrell** [comment]
If you use Bungee I have a plugin laying around somewhere for that, that extends ServerListPlus to add that. I could search it for you if you need it.

**Comment by Twi5TeD** [comment]
sure that would be great

**Comment by Minecrell** [comment]
Thank you for your patience. You can download the plugin from http://minecrell.net/dl/minecraft/plugins/MaximumOnline-1.2.jar, put that in your plugins folder additionally to ServerListPlus. The placeholder is `%max_players%`

**Comment by Twi5TeD** [comment]
i installed to my bungee plugin folder along with slp and it shows this https://gyazo.com/1e0c0e2d910e196d1c7f8f25d2d7fca1 i looked in logs and its also been enabled

**Comment by Twi5TeD** [comment]
oh i looked into the code the placeholder was %max_online% thanks

**Comment by Minecrell** [comment]
Oops, my bad sorry :3
Yep, the placeholder is `%max_online%`.
