### ISSUE TITLE
java.lang.NoSuchMethodError: org.spongepowered.api.plugin.PluginContainer.getVersion()Ljava/lang/String;

### ISSUE THREAD

**Issue by ProsperCraft** [Minecrell/ServerListPlus#82]
http://pastebin.com/15L7GxAx

spongeforge-1.8.9-1763-4.1.0-BETA-1212.jar

and statusprotocol-0.2.jar is installed.

**Comment by Minecrell** [comment]
Install the latest version from https://ci.minecrell.net/job/ServerListPlus/
