### ISSUE TITLE
Favicons do not work, whatsoever.

### ISSUE THREAD

**Issue by Carbonax** [Minecrell/ServerListPlus#83]
I've used PlayerHeads, that works fine.
I use PaperSpigot 1.8.8 with ViaVersion and SLP version 3.4.3 Universal.

Using this config the heads don't load.

>   Favicon:
    URLs:
    - 'http://cravatar.eu/helmavatar/Steve/64.png'

**Comment by Minecrell** [comment]
Please paste your full configuration.

**Comment by Carbonax** [comment]
I sorted it, could you please make the configuration less confusing? I literally spent 2 hours to realise I was editing the wrong section, I needed to edit Custom /

**Comment by Minecrell** [comment]
Sorry! I do plan to improve the configuration in the future. Generally, the second one will be more reliable because it directly gets the skins from Mojang's servers.
