### ISSUE TITLE
RandomPlayer placeholder shows remainder players wrong.

### ISSUE THREAD

**Issue by FrankHG** [Minecrell/ServerListPlus#89]
Using the placeholder:
--
&a%random_players,5|
&a%
--
the remainder '... and XX more ...' will allways show number of players online -1.

If there is 10 players on the server. it will display 5 names and 
'... and 9 more ...'

can you help me with that?

**Comment by Minecrell** [comment]
I'm pretty sure there is an option in the `!Plugin` section for that, something with `Hover` -> `Multiple` and `Dynamic`. You need to set both to true.
