### ISSUE TITLE
ServerListPlus ProtocolLib Error

### ISSUE THREAD

**Issue by Faller10** [Minecrell/ServerListPlus#91]
I tried multiple ServerListPlus and ProtocolLib versions! But everytime I start the server, and hover over the players count, It gives me this error! Could you help me please?
Thanks, and btw, LOVE YOUR PLUGIN!

Obs.: Currently, I'm using ServerListPlus v3.4.4-1.7.X and ProtocolLib 3.6.5.
I'm using Spigot build 

Error: http://pastebin.com/wKh4GdmH

**Comment by Minecrell** [comment]
Please report this to ProtocolLib, I don't think this js something caused by ServerListPlus.
