### ISSUE TITLE
No config file.

### ISSUE THREAD

**Issue by Darthlegos** [Minecrell/ServerListPlus#93]
I looked in the plugins folder, there was no config file. Can you fix this?

**Comment by Minecrell** [comment]
Please post your startup log.

**Comment by Darthlegos** [comment]
I found the problem, thanks!

On Mon, Apr 11, 2016 at 11:52 PM Minecrell <notifications@github.com> wrote:

> Please post your startup log.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Minecrell/ServerListPlus/issues/93#issuecomment-208705058>
>
-- 
Albert Portnoy | Albert.portnoy@gmail.com | 312-833-2266
