### ISSUE TITLE
MOTD Wont Display 

### ISSUE THREAD

**Issue by BobAFK** [Minecrell/ServerListPlus#96]
When I change the motd in the config it just goes back to default
"A Minecraft Server" 
Please reply quick im trying to open the server soon. here is my config [http://pastebin.com/jLmabJaM](url)

**Comment by BobAFK** [comment]
Ive just found out half the reason its now not working and showing as red when i type /plugins it worked about 5 mins ago but since i reloaded to try and get the motd to show its now disabled ? Help!

**Comment by BobAFK** [comment]
This is my config file for SLP [http://pastebin.com/2t6EWaVz](url)

**Comment by Minecrell** [comment]
You got a small syntax mistake in there, try https://gist.githubusercontent.com/Minecrell/f7c148dc44234816e11f9b5ea0cfa7cd/raw/1fc04ba5feb3ce93b25559ed3c9843ae72092d39/ServerListPlus.yml

**Comment by BobAFK** [comment]
Thankyou :D <3
